/DECLARE @LAST_DAILY BIGINT = ISNULL((SELECT SUM(DL.AMOUNT) FROM PAY2_DECREE_LINE/ {
  c\
    DECLARE @LAST_DAILY_ONLY BIGINT = ISNULL((SELECT SUM(DL.AMOUNT) FROM PAY2_DECREE_LINE DL INNER JOIN PAY2_ITEM_DEF ID ON DL.ITEM_ID = ID.ITEM_ID WHERE DL.DEC_ID = @LAST_DEC_ID AND ID.ITEM_TYPE = 1 AND ID.INS_SUBJECT = 1 AND ID.CALC_BASIS = 1), 0);\
    DECLARE @LAST_MONTHLY_ONLY BIGINT = ISNULL((SELECT SUM(DL.AMOUNT) FROM PAY2_DECREE_LINE DL INNER JOIN PAY2_ITEM_DEF ID ON DL.ITEM_ID = ID.ITEM_ID WHERE DL.DEC_ID = @LAST_DEC_ID AND ID.ITEM_TYPE = 1 AND ID.INS_SUBJECT = 1 AND ID.CALC_BASIS = 2), 0);\
    DECLARE @LAST_DAILY BIGINT = @LAST_DAILY_ONLY + CAST(@LAST_MONTHLY_ONLY / 30.0 AS BIGINT);\
    IF @LAST_DAILY < @MIN_WAGE_DAILY SET @LAST_DAILY = @MIN_WAGE_DAILY;\
    DECLARE @LAST_SALARY BIGINT = (@LAST_DAILY * 30);
}
