SELECT COLUMN_NAME, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PAY2_WORKSHOP' AND COLUMN_NAME = 'DEFAULT_DEED_MODE';

SELECT COLUMN_NAME, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PAY2_RUN' AND COLUMN_NAME IN ('DEED_MODE', 'DEED_GENERATOR_VERSION');

SELECT OBJECT_DEFINITION(OBJECT_ID('CK_WS_DEED_MODE')) AS ConstraintDefinition;
