-- === CC_Unit ===
SET IDENTITY_INSERT dbo.CC_Unit ON;
INSERT INTO dbo.CC_Unit (UnitId, UnitName, Depatman, SplitMode, IsActive, SeqNo) VALUES (1, N'واحد اصلی', 1, 1, 1, 1);
INSERT INTO dbo.CC_Unit (UnitId, UnitName, Depatman, SplitMode, IsActive, SeqNo) VALUES (2, N'واحد یزد', 2, 1, 1, 2);
SET IDENTITY_INSERT dbo.CC_Unit OFF;

-- === CC_UnitAnbar ===
INSERT INTO dbo.CC_UnitAnbar (UnitId, Anbar, AnbarRole, DoStockCount, SeqNo) VALUES (1, 1, 2, 1, 2);
INSERT INTO dbo.CC_UnitAnbar (UnitId, Anbar, AnbarRole, DoStockCount, SeqNo) VALUES (1, 2, 3, 1, 3);
INSERT INTO dbo.CC_UnitAnbar (UnitId, Anbar, AnbarRole, DoStockCount, SeqNo) VALUES (1, 3, 3, 1, 5);
INSERT INTO dbo.CC_UnitAnbar (UnitId, Anbar, AnbarRole, DoStockCount, SeqNo) VALUES (1, 7, 1, 1, 1);
INSERT INTO dbo.CC_UnitAnbar (UnitId, Anbar, AnbarRole, DoStockCount, SeqNo) VALUES (1, 8, 4, 1, 4);
INSERT INTO dbo.CC_UnitAnbar (UnitId, Anbar, AnbarRole, DoStockCount, SeqNo) VALUES (1, 10, 3, 1, 6);
INSERT INTO dbo.CC_UnitAnbar (UnitId, Anbar, AnbarRole, DoStockCount, SeqNo) VALUES (1, 14, 3, 1, 7);
INSERT INTO dbo.CC_UnitAnbar (UnitId, Anbar, AnbarRole, DoStockCount, SeqNo) VALUES (1, 15, 3, 1, 1);
INSERT INTO dbo.CC_UnitAnbar (UnitId, Anbar, AnbarRole, DoStockCount, SeqNo) VALUES (2, 807, 3, 1, 3);
INSERT INTO dbo.CC_UnitAnbar (UnitId, Anbar, AnbarRole, DoStockCount, SeqNo) VALUES (2, 808, 3, 1, 5);
INSERT INTO dbo.CC_UnitAnbar (UnitId, Anbar, AnbarRole, DoStockCount, SeqNo) VALUES (2, 810, 1, 1, 1);
INSERT INTO dbo.CC_UnitAnbar (UnitId, Anbar, AnbarRole, DoStockCount, SeqNo) VALUES (2, 811, 2, 1, 2);

-- === CC_UnitAcc ===
INSERT INTO dbo.CC_UnitAcc (UnitId, HesKol, HesMoin, HesTafsili, CostKind, Ratio, IsActive, Note) VALUES (1, 711, NULL, NULL, 1, 1.000000, 1, N'هزينه دستمزد توليد');
INSERT INTO dbo.CC_UnitAcc (UnitId, HesKol, HesMoin, HesTafsili, CostKind, Ratio, IsActive, Note) VALUES (1, 712, NULL, NULL, 1, 1.000000, 1, N'هزينه دستمزد خدمات — سهم توليدي');
INSERT INTO dbo.CC_UnitAcc (UnitId, HesKol, HesMoin, HesTafsili, CostKind, Ratio, IsActive, Note) VALUES (1, 713, NULL, NULL, 1, 1.000000, 1, N'هزينه دستمزد اداري — سهم توليدي');
INSERT INTO dbo.CC_UnitAcc (UnitId, HesKol, HesMoin, HesTafsili, CostKind, Ratio, IsActive, Note) VALUES (1, 721, NULL, NULL, 1, 1.000000, 1, N'ساير هزينه‌هاي توليد');
INSERT INTO dbo.CC_UnitAcc (UnitId, HesKol, HesMoin, HesTafsili, CostKind, Ratio, IsActive, Note) VALUES (1, 723, NULL, NULL, 1, 1.000000, 1, N'ساير هزينه‌هاي اداري — سهم توليدي');
INSERT INTO dbo.CC_UnitAcc (UnitId, HesKol, HesMoin, HesTafsili, CostKind, Ratio, IsActive, Note) VALUES (1, 745, NULL, NULL, 1, 1.000000, 1, N'مرکز هزينه ضايعات و ساير');
INSERT INTO dbo.CC_UnitAcc (UnitId, HesKol, HesMoin, HesTafsili, CostKind, Ratio, IsActive, Note) VALUES (2, 743, NULL, NULL, 1, 1.000000, 1, N'هزينه‌هاي واحد يزد');

-- === CC_AnbarHes ===
INSERT INTO dbo.CC_AnbarHes (Anbar, HesKol, HesMoin, Note) VALUES (1, 121, 1, N'مواد اولیه');
INSERT INTO dbo.CC_AnbarHes (Anbar, HesKol, HesMoin, Note) VALUES (2, 121, 2, N'کالای ساخته‌شده');
INSERT INTO dbo.CC_AnbarHes (Anbar, HesKol, HesMoin, Note) VALUES (3, 121, 3, NULL);
INSERT INTO dbo.CC_AnbarHes (Anbar, HesKol, HesMoin, Note) VALUES (4, 121, 4, NULL);
INSERT INTO dbo.CC_AnbarHes (Anbar, HesKol, HesMoin, Note) VALUES (7, 121, 7, N'مواد مصرفی تولید');
INSERT INTO dbo.CC_AnbarHes (Anbar, HesKol, HesMoin, Note) VALUES (8, 121, 8, N'سایر');
INSERT INTO dbo.CC_AnbarHes (Anbar, HesKol, HesMoin, Note) VALUES (10, 121, 10, NULL);
INSERT INTO dbo.CC_AnbarHes (Anbar, HesKol, HesMoin, Note) VALUES (14, 121, 14, NULL);
INSERT INTO dbo.CC_AnbarHes (Anbar, HesKol, HesMoin, Note) VALUES (15, 121, 15, NULL);
INSERT INTO dbo.CC_AnbarHes (Anbar, HesKol, HesMoin, Note) VALUES (807, 121, 807, N'محصول یزد');
INSERT INTO dbo.CC_AnbarHes (Anbar, HesKol, HesMoin, Note) VALUES (809, 121, 809, NULL);
INSERT INTO dbo.CC_AnbarHes (Anbar, HesKol, HesMoin, Note) VALUES (810, 121, 810, N'مواد مصرفی تولید یزد');
INSERT INTO dbo.CC_AnbarHes (Anbar, HesKol, HesMoin, Note) VALUES (811, 121, 811, N'مواد اولیه یزد');
INSERT INTO dbo.CC_AnbarHes (Anbar, HesKol, HesMoin, Note) VALUES (812, 121, 812, NULL);
INSERT INTO dbo.CC_AnbarHes (Anbar, HesKol, HesMoin, Note) VALUES (813, 121, 813, NULL);

-- === CC_LaborAbsorptionRate ===
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'1', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'10', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'1732', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'1742', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'1786', 0.1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'1787', 0, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'1795', NULL, 0, 1, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'1830', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2319', 0.5, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2534', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2537', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2586', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2587', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2603', 0.2, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2648', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2649', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2657', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2658', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2660', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2735', 0.2, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2765', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2769', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2786', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2791', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2793', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2807', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2812', 0.18, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2813', 0.5, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2889', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'2912', 0.5, 0, 1, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3100', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3127', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3160', 0.4, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3204', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3206', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3217', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3220', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3221', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3222', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3223', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3224', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3225', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3226', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3227', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3228', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3249', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3253', 0.1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3258', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3263', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3271', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3286', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'33', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3301', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3316', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3320', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3322', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3329', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3330', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3331', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3365', NULL, 0, 1, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3369', 0.5, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3465', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3469', 0.2, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3479', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3480', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3499', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3514', NULL, 0, 1, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3515', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3518', 0.8, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3526', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3540', 0.18, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3541', 0.5, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3559', NULL, 0, 1, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'3561', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'366', 0.3, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'368', 0.3, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'373', 0, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'45', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'48', 0.5, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'5', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'82', 0.8, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'88', 0.18, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'89', 0.18, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'90', 0.18, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'93', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'94', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (1, N'95', 0.18, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'16', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'1761', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'19', 0.25, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'20', 0.2, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'2165', 0.1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'2626', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'2882', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'29', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'30', 0.2, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3076', 0.27, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3080', 0.07, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3118', 0.1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3119', 0.1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3123', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3129', 0.2, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3132', 0.15, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3135', 1.3, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3142', 0.6, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3294', 0.8, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3300', 0.15, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3342', 0.2, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3348', 0.225, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3349', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3350', 0.9, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3351', 0.38, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3352', 0.1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3353', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3360', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3445', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3446', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3447', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3457', 0.9, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3459', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3460', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3470', 0.15, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3471', 2, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3477', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3490', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3493', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3496', 0.6, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3500', 0.23, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3503', 0.25, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3511', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3513', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3521', 1.5, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3538', 0.24, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3539', 1.34, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3542', 1, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3555', 1.5, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'3562', 1.3, 0, 0, NULL);
INSERT INTO dbo.CC_LaborAbsorptionRate (UnitId, CODE, Coefficient, OverheadCoefficient, IsFixed, Note) VALUES (2, N'373', 0, 0, 0, NULL);

-- === CC_CheckRule (Threshold/IsActive only) ===
UPDATE dbo.CC_CheckRule SET Threshold = -0.01, IsActive = 1 WHERE RuleCode = 'CHK-01';
UPDATE dbo.CC_CheckRule SET Threshold = NULL, IsActive = 1 WHERE RuleCode = 'CHK-02';
UPDATE dbo.CC_CheckRule SET Threshold = NULL, IsActive = 1 WHERE RuleCode = 'CHK-03';
UPDATE dbo.CC_CheckRule SET Threshold = NULL, IsActive = 1 WHERE RuleCode = 'CHK-04';
UPDATE dbo.CC_CheckRule SET Threshold = NULL, IsActive = 1 WHERE RuleCode = 'CHK-05';
UPDATE dbo.CC_CheckRule SET Threshold = NULL, IsActive = 1 WHERE RuleCode = 'CHK-06';
UPDATE dbo.CC_CheckRule SET Threshold = 0.001, IsActive = 1 WHERE RuleCode = 'CHK-07';
UPDATE dbo.CC_CheckRule SET Threshold = NULL, IsActive = 1 WHERE RuleCode = 'CHK-08';
UPDATE dbo.CC_CheckRule SET Threshold = 0.001, IsActive = 1 WHERE RuleCode = 'CHK-09';
UPDATE dbo.CC_CheckRule SET Threshold = 1e+007, IsActive = 1 WHERE RuleCode = 'CHK-10';
UPDATE dbo.CC_CheckRule SET Threshold = NULL, IsActive = 1 WHERE RuleCode = 'CHK-11';
UPDATE dbo.CC_CheckRule SET Threshold = NULL, IsActive = 1 WHERE RuleCode = 'CHK-12';
UPDATE dbo.CC_CheckRule SET Threshold = NULL, IsActive = 1 WHERE RuleCode = 'CHK-13';
UPDATE dbo.CC_CheckRule SET Threshold = NULL, IsActive = 1 WHERE RuleCode = 'CHK-14';
UPDATE dbo.CC_CheckRule SET Threshold = NULL, IsActive = 1 WHERE RuleCode = 'CHK-15';
UPDATE dbo.CC_CheckRule SET Threshold = NULL, IsActive = 1 WHERE RuleCode = 'CHK-16';
UPDATE dbo.CC_CheckRule SET Threshold = NULL, IsActive = 1 WHERE RuleCode = 'CHK-17';
UPDATE dbo.CC_CheckRule SET Threshold = NULL, IsActive = 1 WHERE RuleCode = 'CHK-18';
UPDATE dbo.CC_CheckRule SET Threshold = NULL, IsActive = 1 WHERE RuleCode = 'CHK-19';
UPDATE dbo.CC_CheckRule SET Threshold = NULL, IsActive = 1 WHERE RuleCode = 'CHK-20';
