-- Requested report access for NEWPOODR1405 user 35; no payroll write permissions.
SET XACT_ABORT ON;
IF DB_NAME() NOT IN (N'NEWPOODR1405', N'SafirTestPoodr20261001')
    THROW 50000, 'This script is only for the approved Poodr database or its test copy.', 1;
IF NOT EXISTS (SELECT 1 FROM dbo.SALA_DTL WHERE IDD=35 AND ENABL=0)
    THROW 50000, 'Expected active user 35 was not found.', 1;
BEGIN TRANSACTION;
INSERT dbo.SAL_CHEK(USERCO,[OBJECT],RUN,SEE,INP,UPD,DEL,CRT)
SELECT 35,F.IDH,CASE WHEN F.FORMNAME IN (N'PAY2_REPORTS',N'PAY2_RUN') THEN 1 ELSE 0 END,1,0,0,0,GETDATE()
FROM dbo.TFORMS F
WHERE F.FORMNAME IN (N'PAY2_REPORTS',N'PAY2_RUN',N'PAY2_WORKSHOP',N'PAY2_ATTENDANCE',N'PAY2_EMPLOYEE')
 AND NOT EXISTS(SELECT 1 FROM dbo.SAL_CHEK S WHERE S.USERCO=35 AND S.[OBJECT]=F.IDH);
UPDATE S SET SEE=1,
 RUN=CASE WHEN F.FORMNAME IN (N'PAY2_REPORTS',N'PAY2_RUN') THEN 1 ELSE S.RUN END
FROM dbo.SAL_CHEK S JOIN dbo.TFORMS F ON F.IDH=S.[OBJECT]
WHERE S.USERCO=35 AND F.FORMNAME IN (N'PAY2_REPORTS',N'PAY2_RUN',N'PAY2_WORKSHOP',N'PAY2_ATTENDANCE',N'PAY2_EMPLOYEE');
IF NOT EXISTS(SELECT 1 FROM dbo.PAY2_USER_WS WHERE USERCO=35 AND WS_ID=1)
 INSERT dbo.PAY2_USER_WS(USERCO,WS_ID,CRT) VALUES(35,1,GETDATE());
COMMIT;
