/*
  Safir/Jules legacy dependency schema
  Generated from the production SQL Server 2022 schema exports.
  Run this file BEFORE Server/Database/schema.sql.
  Contains exactly the 14 parent/legacy tables required by the Safir PAY2 test schema.
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE [dbo].[TCOD_BANKS](
    [CODE] [int] NOT NULL,
    [NAMES] [nvarchar](32) NOT NULL,
    [IDD] [int] IDENTITY(1,1) NOT NULL,
    [TEJ_C] [int] NULL,
    [MEL_C] [int] NULL,
    [SAD_C] [int] NULL,
    [MLA_C] [int] NULL,
    [REF_C] [int] NULL,
    [TOS_C] [int] NULL,
    [KES_C] [int] NULL,
    [KAR_C] [int] NULL,
    [POS_C] [int] NULL,
    [TAT_C] [int] NULL,
    [SEP_C] [int] NULL,
    [TSA_C] [int] NULL,
    [SAN_C] [int] NULL,
    [MAS_C] [int] NULL,
    [EGH_C] [int] NULL,
    [PAR_C] [int] NULL,
    [PAS_C] [int] NULL,
    [DEY_C] [int] NULL,
    [SAM_C] [int] NULL,
    [SAR_C] [int] NULL,
    [SIN_C] [int] NULL,
    [SHA_C] [int] NULL,
    [CRT] [datetime] NULL,
    [UID] [int] NULL,
 CONSTRAINT [aaaaaTCOD_BANKS_PK] PRIMARY KEY NONCLUSTERED
(
    [CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__TEJ_C__544C7222] DEFAULT ((0)) FOR [TEJ_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__MEL_C__5540965B] DEFAULT ((0)) FOR [MEL_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__SAD_C__5634BA94] DEFAULT ((0)) FOR [SAD_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__MLA_C__5728DECD] DEFAULT ((0)) FOR [MLA_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__REF_C__581D0306] DEFAULT ((0)) FOR [REF_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__TOS_C__5911273F] DEFAULT ((0)) FOR [TOS_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__KES_C__5A054B78] DEFAULT ((0)) FOR [KES_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__KAR_C__5AF96FB1] DEFAULT ((0)) FOR [KAR_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__POS_C__5BED93EA] DEFAULT ((0)) FOR [POS_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__TAT_C__5CE1B823] DEFAULT ((0)) FOR [TAT_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__SEP_C__5DD5DC5C] DEFAULT ((0)) FOR [SEP_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__TSA_C__5ECA0095] DEFAULT ((0)) FOR [TSA_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__SAN_C__5FBE24CE] DEFAULT ((0)) FOR [SAN_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__MAS_C__60B24907] DEFAULT ((0)) FOR [MAS_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__EGH_C__61A66D40] DEFAULT ((0)) FOR [EGH_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__PAR_C__629A9179] DEFAULT ((0)) FOR [PAR_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__PAS_C__638EB5B2] DEFAULT ((0)) FOR [PAS_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__DEY_C__6482D9EB] DEFAULT ((0)) FOR [DEY_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__SAM_C__6576FE24] DEFAULT ((0)) FOR [SAM_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__SAR_C__666B225D] DEFAULT ((0)) FOR [SAR_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__SIN_C__675F4696] DEFAULT ((0)) FOR [SIN_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__SHA_C__68536ACF] DEFAULT ((0)) FOR [SHA_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANKS__CRT__69F19A7E] DEFAULT (getdate()) FOR [CRT];
GO

CREATE TABLE [dbo].[TASKS](
    [IDNUM] [int] IDENTITY(1,1) NOT NULL,
    [GR] [int] NULL,
    [PERSONEL] [int] NULL,
    [TASK] [nvarchar](4000) NULL,
    [PERIORITY] [int] NULL,
    [STATUS] [int] NULL,
    [STDATE] [int] NULL,
    [STTIME] [int] NULL,
    [ENDATE] [int] NULL,
    [ENTIME] [int] NULL,
    [USERNAME] [nvarchar](50) NULL,
    [COMP_COD] [nvarchar](50) NOT NULL,
    [SUMTIME] [int] NULL,
    [pic] [image] NULL,
    [ss] [float] NULL,
    [skid] [int] NULL,
    [num] [bigint] NULL,
    [tg] [bigint] NULL,
    [CTIM] [datetime] NULL,
    [USERCO] [int] NULL,
    [SEE] [int] NULL,
    [SEET] [datetime] NULL,
    [CRT] [datetime] NULL,
    [UID] [int] NULL,
 CONSTRAINT [PK_TASKS] PRIMARY KEY CLUSTERED
(
    [IDNUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
GO
ALTER TABLE [dbo].[TASKS] ADD CONSTRAINT [DF_TASKS_PERIORITY] DEFAULT ((2)) FOR [PERIORITY];
GO
ALTER TABLE [dbo].[TASKS] ADD CONSTRAINT [DF_TASKS_STATUS] DEFAULT ((1)) FOR [STATUS];
GO
ALTER TABLE [dbo].[TASKS] ADD CONSTRAINT [DF_TASKS_CTIM] DEFAULT (getdate()) FOR [CTIM];
GO
ALTER TABLE [dbo].[TASKS] ADD CONSTRAINT [DF__TASKS__SEE__6BE95960] DEFAULT ((0)) FOR [SEE];
GO
ALTER TABLE [dbo].[TASKS] ADD CONSTRAINT [DF__TASKS__CRT__6CDD7D99] DEFAULT (getdate()) FOR [CRT];
GO

CREATE TABLE [dbo].[CUSTKIND](
	[CUST_COD] [int] NOT NULL,
	[CUSTKNAME] [nvarchar](50) NOT NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
 CONSTRAINT [aaaaaCUSTKIND_PK] PRIMARY KEY NONCLUSTERED 
(
	[CUST_COD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[DEPART](
	[DEPATMAN] [int] NOT NULL,
	[DEPNAME] [nvarchar](100) NOT NULL,
	[IDD] [int] IDENTITY(1,1) NOT NULL,
	[DEPART] [nvarchar](200) NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
	[PCODE] [nvarchar](10) NULL,
	[BBC] [nvarchar](50) NULL,
 CONSTRAINT [aaaaaDEPART_PK] PRIMARY KEY NONCLUSTERED 
(
	[DEPATMAN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[DETA_HES](
	[N_KOL] [int] NOT NULL,
	[NUMBER] [int] NOT NULL,
	[NAME] [nvarchar](100) NULL,
	[TOZIH] [nvarchar](40) NULL,
	[BED_BES] [float] NULL,
	[ADDRESS] [nvarchar](100) NULL,
	[TEL] [nvarchar](50) NULL,
	[CODE_E] [nvarchar](20) NULL,
	[USERCO] [int] NULL,
	[USER_NAME] [nvarchar](50) NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [aaaaaDETA_HES_PK] PRIMARY KEY NONCLUSTERED 
(
	[N_KOL] ASC,
	[NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[PRICE_ELAMIE](
	[PEPID] [int] NOT NULL,
	[PEPNAME] [nvarchar](250) NOT NULL,
	[PEPDATE] [int] NOT NULL,
	[TR_DATE] [datetime] NOT NULL,
	[USERNAME] [nvarchar](50) NOT NULL,
	[SGN1] [bit] NOT NULL,
	[SGN2] [bit] NOT NULL,
	[SGN3] [bit] NOT NULL,
	[SGN4] [bit] NOT NULL,
	[PEPDEPART] [int] NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
 CONSTRAINT [PK_PRICE_ELAMIE] PRIMARY KEY CLUSTERED 
(
	[PEPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[PRICE_ELAMIETF](
	[PEID] [int] NOT NULL,
	[PENAME] [nvarchar](250) NOT NULL,
	[PEDATE] [int] NOT NULL,
	[TR_DATE] [datetime] NOT NULL,
	[USERNAME] [nvarchar](50) NOT NULL,
	[SGN1] [bit] NOT NULL,
	[SGN2] [bit] NOT NULL,
	[SGN3] [bit] NOT NULL,
	[SGN4] [bit] NOT NULL,
	[PEPDEPART] [int] NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
 CONSTRAINT [PK_PRICE_ELAMIETF] PRIMARY KEY CLUSTERED 
(
	[PEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[PRICE_PAYNO](
	[PPID] [int] NOT NULL,
	[PPAME] [nvarchar](250) NOT NULL,
	[TR_DATE] [datetime] NOT NULL,
	[USERNAME] [nvarchar](50) NOT NULL,
	[MODAT] [int] NOT NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
 CONSTRAINT [PK_PRICE_PAYNO] PRIMARY KEY CLUSTERED 
(
	[PPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[SHIFT](
	[SHIFT_ID] [int] NOT NULL,
	[SHNAME] [nvarchar](20) NOT NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
 CONSTRAINT [aaaaaSHIFT_PK] PRIMARY KEY NONCLUSTERED 
(
	[SHIFT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TCOD_HESGROUP](
	[CODE] [float] NOT NULL,
	[NAMES] [nvarchar](50) NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
 CONSTRAINT [aaaaaTCOD_HESGROUP_PK] PRIMARY KEY NONCLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TCOD_HESKIND](
	[CODE] [float] NOT NULL,
	[NAMES] [nvarchar](32) NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
 CONSTRAINT [aaaaaTCOD_HESKIND_PK] PRIMARY KEY NONCLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TCOD_HESVAZ](
	[CODE] [float] NOT NULL,
	[NAMES] [nvarchar](32) NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
 CONSTRAINT [aaaaaTCOD_HESVAZ_PK] PRIMARY KEY NONCLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TDETA_HES](
	[N_KOL] [int] NOT NULL,
	[NUMBER] [int] NOT NULL,
	[TNUMBER] [int] NOT NULL,
	[NAME] [nvarchar](100) NULL,
	[TOZIH] [nvarchar](255) NULL,
	[BED_BES] [float] NULL,
	[ADDRESS] [nvarchar](100) NULL,
	[TEL] [nvarchar](50) NULL,
	[CODE_E] [nvarchar](20) NULL,
	[IDD] [int] IDENTITY(1,1) NOT NULL,
	[ECODE] [nvarchar](20) NULL,
	[PCODE] [nvarchar](10) NULL,
	[IYALAT] [nvarchar](20) NULL,
	[CITY] [nvarchar](20) NULL,
	[MCODEM] [nvarchar](20) NULL,
	[CUST_COD] [int] NULL,
	[MOBILE] [nvarchar](55) NULL,
	[ROUTE_NAME] [nvarchar](50) NULL,
	[Longitude] [float] NULL,
	[Latitude] [float] NULL,
	[OSTANID] [int] NULL,
	[SHAHRID] [int] NULL,
	[USERCO] [int] NULL,
	[USER_NAME] [nvarchar](50) NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
	[tob] [int] NULL,
 CONSTRAINT [PK_TDETA_HES] PRIMARY KEY CLUSTERED 
(
	[N_KOL] ASC,
	[NUMBER] ASC,
	[TNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_TDETA_HES_NAME] UNIQUE NONCLUSTERED 
(
	[N_KOL] ASC,
	[NUMBER] ASC,
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TOTA_HES](
	[NUMBER] [int] NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[NO_HES] [float] NULL,
	[M_D] [float] NULL,
	[GROUP] [float] NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [aaaaaTOTA_HES_PK] PRIMARY KEY NONCLUSTERED 
(
	[NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTKIND] ADD  CONSTRAINT [DF__CUSTKIND__CRT__0B1D841F]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[DEPART] ADD  CONSTRAINT [DF__DEPART__CRT__5B6E70FD]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[DETA_HES] ADD  CONSTRAINT [DF__DETA_HES__N_KOL__15DA3E5D]  DEFAULT ((0)) FOR [N_KOL]
GO
ALTER TABLE [dbo].[DETA_HES] ADD  CONSTRAINT [DF__DETA_HES__NUMBER__16CE6296]  DEFAULT ((0)) FOR [NUMBER]
GO
ALTER TABLE [dbo].[DETA_HES] ADD  CONSTRAINT [DF__DETA_HES__CRT__67152DD3]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[PRICE_ELAMIE] ADD  CONSTRAINT [DF_PRICE_ELAMIE_SGN1]  DEFAULT ((0)) FOR [SGN1]
GO
ALTER TABLE [dbo].[PRICE_ELAMIE] ADD  CONSTRAINT [DF_PRICE_ELAMIE_SGN2]  DEFAULT ((0)) FOR [SGN2]
GO
ALTER TABLE [dbo].[PRICE_ELAMIE] ADD  CONSTRAINT [DF_PRICE_ELAMIE_SGN3]  DEFAULT ((0)) FOR [SGN3]
GO
ALTER TABLE [dbo].[PRICE_ELAMIE] ADD  CONSTRAINT [DF_PRICE_ELAMIE_SGN4]  DEFAULT ((0)) FOR [SGN4]
GO
ALTER TABLE [dbo].[PRICE_ELAMIE] ADD  CONSTRAINT [DF__PRICE_ELAMI__CRT__3A42875C]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[PRICE_ELAMIETF] ADD  CONSTRAINT [DF_PRICE_ELAMIETF_SGN1]  DEFAULT ((0)) FOR [SGN1]
GO
ALTER TABLE [dbo].[PRICE_ELAMIETF] ADD  CONSTRAINT [DF_PRICE_ELAMIETF_SGN2]  DEFAULT ((0)) FOR [SGN2]
GO
ALTER TABLE [dbo].[PRICE_ELAMIETF] ADD  CONSTRAINT [DF_PRICE_ELAMIETF_SGN3]  DEFAULT ((0)) FOR [SGN3]
GO
ALTER TABLE [dbo].[PRICE_ELAMIETF] ADD  CONSTRAINT [DF_PRICE_ELAMIETF_SGN4]  DEFAULT ((0)) FOR [SGN4]
GO
ALTER TABLE [dbo].[PRICE_ELAMIETF] ADD  CONSTRAINT [DF__PRICE_ELAMI__CRT__45B43A08]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[PRICE_PAYNO] ADD  CONSTRAINT [DF__PRICE_PAY__MODAT__41A3B202]  DEFAULT ((0)) FOR [MODAT]
GO
ALTER TABLE [dbo].[PRICE_PAYNO] ADD  CONSTRAINT [DF__PRICE_PAYNO__CRT__4A78EF25]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[SHIFT] ADD  CONSTRAINT [DF__SHIFT__CRT__3C2ACFCE]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[TCOD_HESGROUP] ADD  CONSTRAINT [DF__TCOD_HESGRO__CRT__02883E1E]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[TCOD_HESKIND] ADD  CONSTRAINT [DF__TCOD_HESKIN__CRT__7EB7AD3A]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[TCOD_HESVAZ] ADD  CONSTRAINT [DF__TCOD_HESVAZ__CRT__780AAFAB]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[TDETA_HES] ADD  CONSTRAINT [DF__TDETA_HES__CODE___7DCDAAA2]  DEFAULT ('0') FOR [CODE_E]
GO
ALTER TABLE [dbo].[TDETA_HES] ADD  CONSTRAINT [DF__TDETA_HES__CRT__4A43E4FB]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[TDETA_HES] ADD  CONSTRAINT [DF__TDETA_HES__tob__20389C96]  DEFAULT ((2)) FOR [tob]
GO
ALTER TABLE [dbo].[TOTA_HES] ADD  CONSTRAINT [DF__TOTA_HES__NUMBER__075714DC]  DEFAULT ((0)) FOR [NUMBER]
GO
ALTER TABLE [dbo].[TOTA_HES] ADD  CONSTRAINT [DF__TOTA_HES__NO_HES__084B3915]  DEFAULT ((0)) FOR [NO_HES]
GO
ALTER TABLE [dbo].[TOTA_HES] ADD  CONSTRAINT [DF__TOTA_HES__M_D__093F5D4E]  DEFAULT ((0)) FOR [M_D]
GO
ALTER TABLE [dbo].[TOTA_HES] ADD  CONSTRAINT [DF__TOTA_HES__GROUP__0A338187]  DEFAULT ((0)) FOR [GROUP]
GO
ALTER TABLE [dbo].[TOTA_HES] ADD  CONSTRAINT [DF__TOTA_HES__CRT__40BA7AC1]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[DETA_HES]  WITH NOCHECK ADD  CONSTRAINT [DETA_HES_FK00] FOREIGN KEY([N_KOL])
REFERENCES [dbo].[TOTA_HES] ([NUMBER])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[DETA_HES] CHECK CONSTRAINT [DETA_HES_FK00]
GO
ALTER TABLE [dbo].[TDETA_HES]  WITH NOCHECK ADD  CONSTRAINT [FK_TDETA_HES_DETA_HES] FOREIGN KEY([N_KOL], [NUMBER])
REFERENCES [dbo].[DETA_HES] ([N_KOL], [NUMBER])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TDETA_HES] CHECK CONSTRAINT [FK_TDETA_HES_DETA_HES]
GO
ALTER TABLE [dbo].[TOTA_HES]  WITH NOCHECK ADD  CONSTRAINT [TOTA_HES_FK00] FOREIGN KEY([NO_HES])
REFERENCES [dbo].[TCOD_HESKIND] ([CODE])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TOTA_HES] CHECK CONSTRAINT [TOTA_HES_FK00]
GO
ALTER TABLE [dbo].[TOTA_HES]  WITH NOCHECK ADD  CONSTRAINT [TOTA_HES_FK01] FOREIGN KEY([M_D])
REFERENCES [dbo].[TCOD_HESVAZ] ([CODE])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TOTA_HES] CHECK CONSTRAINT [TOTA_HES_FK01]
GO
ALTER TABLE [dbo].[TOTA_HES]  WITH NOCHECK ADD  CONSTRAINT [TOTA_HES_FK02] FOREIGN KEY([GROUP])
REFERENCES [dbo].[TCOD_HESGROUP] ([CODE])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TOTA_HES] CHECK CONSTRAINT [TOTA_HES_FK02]
GO

/* ============================================================
   Legacy inventory/item dependencies required by schema.sql
   Dependency order:
   TCOD_ANBAR_KIND
   TCOD_ANBAR
   TCOD_STUFGROUP
   TCOD_VAHEDS
   STUF_DEF
   STUF_FSK
   STUF_STK
   ============================================================ */

CREATE TABLE [dbo].[TCOD_ANBAR_KIND](
    [CODE] [int] NOT NULL,
    [ANB_KIND] [nvarchar](50) NULL,
    [CRT] [datetime] NULL,
    [UID] [int] NULL,
 CONSTRAINT [PK_TCOD_ANBAR_KIND] PRIMARY KEY CLUSTERED
(
    [CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
       ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON,
       OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TCOD_ANBAR](
    [CODE] [int] NOT NULL,
    [NAMES] [nvarchar](32) NOT NULL,
    [KIND] [int] NOT NULL,
    [idd] [int] IDENTITY(1,1) NOT NULL,
    [CRT] [datetime] NULL,
    [UID] [int] NULL,
 CONSTRAINT [aaaaaTCOD_ANBAR_PK] PRIMARY KEY NONCLUSTERED
(
    [CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
       ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON,
       OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TCOD_STUFGROUP](
    [CODE] [float] NOT NULL,
    [NAMES] [nvarchar](32) NULL,
    [pic] [image] NULL,
    [tic] [bit] NULL,
    [MEGHTA] [float] NULL,
    [MEGHJAY] [float] NULL,
    [CRT] [datetime] NULL,
    [UID] [int] NULL,
 CONSTRAINT [aaaaaTCOD_STUFGROUP_PK] PRIMARY KEY NONCLUSTERED
(
    [CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
       ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON,
       OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[TCOD_VAHEDS](
    [CODE] [int] NOT NULL,
    [NAMES] [nvarchar](32) NOT NULL,
    [CRT] [datetime] NULL,
    [UID] [int] NULL,
 CONSTRAINT [aaaaaTCOD_VAHEDS_PK] PRIMARY KEY NONCLUSTERED
(
    [CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
       ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON,
       OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[STUF_DEF](
    [CODE] [nvarchar](15) NOT NULL,
    [NAME] [nvarchar](80) NULL,
    [N_FANI] [nvarchar](30) NULL,
    [TOZIH] [nvarchar](40) NULL,
    [VAHED] [int] NOT NULL,
    [B_SEF] [float] NOT NULL,
    [N_SEF] [float] NOT NULL,
    [MIN_M] [float] NOT NULL,
    [MAX_M] [float] NOT NULL,
    [RADAH] [float] NOT NULL,
    [KINDK] [smallint] NULL,
    [MABL_F] [float] NOT NULL,
    [DEPART] [int] NULL,
    [IDD] [int] IDENTITY(1,1) NOT NULL,
    [CMBAA] [bit] NULL,
    [VAZN] [float] NULL,
    [OKF] [bit] NULL,
    [MENUIT] [float] NULL,
    [MEGHTA] [float] NULL,
    [MEGHJAY] [float] NULL,
    [PGID] [int] NULL,
    [BARCODE] [nvarchar](100) NULL,
    [CRT] [datetime] NULL,
    [UID] [int] NULL,
    [mu] [int] NULL,
    [sstid] [nvarchar](13) NULL,
    [vra] [float] NULL,
 CONSTRAINT [aaaaaSTUF_DEF_PK] PRIMARY KEY NONCLUSTERED
(
    [CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
       ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON,
       OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[STUF_FSK](
    [CODE] [nvarchar](15) NOT NULL,
    [ANBAR] [int] NOT NULL,
    [MOGODI_A] [float] NOT NULL,
    [FI_A] [float] NOT NULL,
    [MABL_A] [float] NOT NULL,
    [MANDAH_A] [float] NOT NULL,
    [VAZ] [float] NULL,
    [IDD] [int] IDENTITY(1,1) NOT NULL,
    [POSITION] [nvarchar](30) NULL,
    [B_SEF] [float] NULL,
    [N_SEF] [float] NULL,
    [MIN_M] [float] NULL,
    [MAX_M] [float] NULL,
    [CRT] [datetime] NULL,
    [UID] [int] NULL,
 CONSTRAINT [aaaaaSTUF_FSK_PK] PRIMARY KEY NONCLUSTERED
(
    [CODE] ASC,
    [ANBAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
       ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON,
       OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[STUF_STK](
    [CODE] [nvarchar](15) NOT NULL,
    [ANBAR] [int] NOT NULL,
    [MOGODI_A] [float] NOT NULL,
    [MOGODI] [float] NOT NULL,
    [MABL_M] [float] NOT NULL,
    [CRT] [datetime] NULL,
    [UID] [int] NULL,
 CONSTRAINT [aaaaaSTUF_STK_PK] PRIMARY KEY NONCLUSTERED
(
    [CODE] ASC,
    [ANBAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
       ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON,
       OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[STUF_DEF] ADD CONSTRAINT [DF__STUF_DEF__B_SEF__6225902D] DEFAULT ((0)) FOR [B_SEF]
GO
ALTER TABLE [dbo].[STUF_DEF] ADD CONSTRAINT [DF__STUF_DEF__N_SEF__6319B466] DEFAULT ((0)) FOR [N_SEF]
GO
ALTER TABLE [dbo].[STUF_DEF] ADD CONSTRAINT [DF__STUF_DEF__MIN_M__640DD89F] DEFAULT ((0)) FOR [MIN_M]
GO
ALTER TABLE [dbo].[STUF_DEF] ADD CONSTRAINT [DF__STUF_DEF__MAX_M__6501FCD8] DEFAULT ((0)) FOR [MAX_M]
GO
ALTER TABLE [dbo].[STUF_DEF] ADD CONSTRAINT [DF__STUF_DEF__KINDK__65F62111] DEFAULT ((0)) FOR [KINDK]
GO
ALTER TABLE [dbo].[STUF_DEF] ADD CONSTRAINT [DF__STUF_DEF__MABL_F__66EA454A] DEFAULT ((0)) FOR [MABL_F]
GO
ALTER TABLE [dbo].[STUF_DEF] ADD CONSTRAINT [DF__STUF_DEF__CMBAA__02133CD2] DEFAULT ((0)) FOR [CMBAA]
GO
ALTER TABLE [dbo].[STUF_DEF] ADD CONSTRAINT [DF__STUF_DEF__VAZN__0307610B] DEFAULT ((0)) FOR [VAZN]
GO
ALTER TABLE [dbo].[STUF_DEF] ADD CONSTRAINT [DF__STUF_DEF__MEGHTA__03FB8544] DEFAULT ((0)) FOR [MEGHTA]
GO
ALTER TABLE [dbo].[STUF_DEF] ADD CONSTRAINT [DF__STUF_DEF__MEGHJA__04EFA97D] DEFAULT ((0)) FOR [MEGHJAY]
GO
ALTER TABLE [dbo].[STUF_DEF] ADD CONSTRAINT [DF__STUF_DEF__CRT__17B8652E] DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[STUF_DEF] ADD CONSTRAINT [DF__STUF_DEF__vra__75193467] DEFAULT ((9)) FOR [vra]
GO

ALTER TABLE [dbo].[STUF_FSK] ADD CONSTRAINT [DF__STUF_FSK__MOGODI__567ED357] DEFAULT ((0)) FOR [MOGODI_A]
GO
ALTER TABLE [dbo].[STUF_FSK] ADD CONSTRAINT [DF__STUF_FSK__FI_A__5772F790] DEFAULT ((0)) FOR [FI_A]
GO
ALTER TABLE [dbo].[STUF_FSK] ADD CONSTRAINT [DF__STUF_FSK__MABL_A__58671BC9] DEFAULT ((0)) FOR [MABL_A]
GO
ALTER TABLE [dbo].[STUF_FSK] ADD CONSTRAINT [DF__STUF_FSK__MANDAH__595B4002] DEFAULT ((0)) FOR [MANDAH_A]
GO
ALTER TABLE [dbo].[STUF_FSK] ADD CONSTRAINT [DF__STUF_FSK__CRT__2235F3A1] DEFAULT (getdate()) FOR [CRT]
GO

ALTER TABLE [dbo].[STUF_STK] ADD CONSTRAINT [DF__STUF_STK__MOGODI__4B0D20AB] DEFAULT ((0)) FOR [MOGODI_A]
GO
ALTER TABLE [dbo].[STUF_STK] ADD CONSTRAINT [DF__STUF_STK__MOGODI__4C0144E4] DEFAULT ((0)) FOR [MOGODI]
GO
ALTER TABLE [dbo].[STUF_STK] ADD CONSTRAINT [DF__STUF_STK__MABL_M__4CF5691D] DEFAULT ((0)) FOR [MABL_M]
GO
ALTER TABLE [dbo].[STUF_STK] ADD CONSTRAINT [DF__STUF_STK__CRT__448B0BA5] DEFAULT (getdate()) FOR [CRT]
GO

ALTER TABLE [dbo].[TCOD_ANBAR] ADD CONSTRAINT [DF__TCOD_ANBAR__KIND__467D75B8] DEFAULT ((0)) FOR [KIND]
GO
ALTER TABLE [dbo].[TCOD_ANBAR] ADD CONSTRAINT [DF__TCOD_ANBAR__CRT__241E3C13] DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[TCOD_ANBAR_KIND] ADD CONSTRAINT [DF__TCOD_ANBAR__CODE__4B422AD5] DEFAULT ((0)) FOR [CODE]
GO
ALTER TABLE [dbo].[TCOD_ANBAR_KIND] ADD CONSTRAINT [DF__TCOD_ANBAR___CRT__6EB64F9B] DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[TCOD_STUFGROUP] ADD CONSTRAINT [DF__TCOD_STUF__MEGHT__5E0AE686] DEFAULT ((0)) FOR [MEGHTA]
GO
ALTER TABLE [dbo].[TCOD_STUFGROUP] ADD CONSTRAINT [DF__TCOD_STUF__MEGHJ__5EFF0ABF] DEFAULT ((0)) FOR [MEGHJAY]
GO
ALTER TABLE [dbo].[TCOD_STUFGROUP] ADD CONSTRAINT [DF__TCOD_STUFGR__CRT__64F7DB37] DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[TCOD_VAHEDS] ADD CONSTRAINT [DF__TCOD_VAHEDS__CRT__630F92C5] DEFAULT (getdate()) FOR [CRT]
GO

ALTER TABLE [dbo].[TCOD_ANBAR] WITH NOCHECK ADD CONSTRAINT [FK_TCOD_ANBAR_TCOD_ANBAR_KIND]
FOREIGN KEY([KIND]) REFERENCES [dbo].[TCOD_ANBAR_KIND] ([CODE])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TCOD_ANBAR] CHECK CONSTRAINT [FK_TCOD_ANBAR_TCOD_ANBAR_KIND]
GO

ALTER TABLE [dbo].[STUF_DEF] WITH NOCHECK ADD CONSTRAINT [FK_STUF_DEF_TCOD_STUFGROUP]
FOREIGN KEY([RADAH]) REFERENCES [dbo].[TCOD_STUFGROUP] ([CODE])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[STUF_DEF] CHECK CONSTRAINT [FK_STUF_DEF_TCOD_STUFGROUP]
GO

ALTER TABLE [dbo].[STUF_DEF] WITH NOCHECK ADD CONSTRAINT [FK_STUF_DEF_TCOD_VAHEDS]
FOREIGN KEY([VAHED]) REFERENCES [dbo].[TCOD_VAHEDS] ([CODE])
GO
ALTER TABLE [dbo].[STUF_DEF] CHECK CONSTRAINT [FK_STUF_DEF_TCOD_VAHEDS]
GO

ALTER TABLE [dbo].[STUF_FSK] WITH NOCHECK ADD CONSTRAINT [STUF_FSK_FK00]
FOREIGN KEY([CODE]) REFERENCES [dbo].[STUF_DEF] ([CODE])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[STUF_FSK] CHECK CONSTRAINT [STUF_FSK_FK00]
GO

ALTER TABLE [dbo].[STUF_FSK] WITH NOCHECK ADD CONSTRAINT [STUF_FSK_FK01]
FOREIGN KEY([ANBAR]) REFERENCES [dbo].[TCOD_ANBAR] ([CODE])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[STUF_FSK] CHECK CONSTRAINT [STUF_FSK_FK01]
GO

ALTER TABLE [dbo].[STUF_STK] WITH NOCHECK ADD CONSTRAINT [STUF_STK_FK00]
FOREIGN KEY([CODE], [ANBAR]) REFERENCES [dbo].[STUF_FSK] ([CODE], [ANBAR])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[STUF_STK] CHECK CONSTRAINT [STUF_STK_FK00]
GO

PRINT N'Legacy dependency schema source loaded successfully.';
GO
