/*
  Safir/Jules legacy dependency schema
  Generated from the production SQL Server 2022 schema exports.
  Run this file BEFORE Server/Database/schema.sql.
  Contains exactly the 14 parent/legacy tables required by the Safir PAY2 test schema.
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

CREATE TABLE [dbo].[TCOD_BANKS](
    [CODE] [int] NOT NULL,
    [NAMES] [nvarchar](32) NOT NULL,
    [IDD] [int] IDENTITY(1,1) NOT NULL,
    [TEJ_C] [int] NULL,
    [MEL_C] [int] NULL,
    [SAD_C] [int] NULL,
    [MLA_C] [int] NULL,
    [REF_C] [int] NULL,
    [TOS_C] [int] NULL,
    [KES_C] [int] NULL,
    [KAR_C] [int] NULL,
    [POS_C] [int] NULL,
    [TAT_C] [int] NULL,
    [SEP_C] [int] NULL,
    [TSA_C] [int] NULL,
    [SAN_C] [int] NULL,
    [MAS_C] [int] NULL,
    [EGH_C] [int] NULL,
    [PAR_C] [int] NULL,
    [PAS_C] [int] NULL,
    [DEY_C] [int] NULL,
    [SAM_C] [int] NULL,
    [SAR_C] [int] NULL,
    [SIN_C] [int] NULL,
    [SHA_C] [int] NULL,
    [CRT] [datetime] NULL,
    [UID] [int] NULL,
 CONSTRAINT [aaaaaTCOD_BANKS_PK] PRIMARY KEY NONCLUSTERED
(
    [CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__TEJ_C__544C7222] DEFAULT ((0)) FOR [TEJ_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__MEL_C__5540965B] DEFAULT ((0)) FOR [MEL_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__SAD_C__5634BA94] DEFAULT ((0)) FOR [SAD_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__MLA_C__5728DECD] DEFAULT ((0)) FOR [MLA_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__REF_C__581D0306] DEFAULT ((0)) FOR [REF_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__TOS_C__5911273F] DEFAULT ((0)) FOR [TOS_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__KES_C__5A054B78] DEFAULT ((0)) FOR [KES_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__KAR_C__5AF96FB1] DEFAULT ((0)) FOR [KAR_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__POS_C__5BED93EA] DEFAULT ((0)) FOR [POS_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__TAT_C__5CE1B823] DEFAULT ((0)) FOR [TAT_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__SEP_C__5DD5DC5C] DEFAULT ((0)) FOR [SEP_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__TSA_C__5ECA0095] DEFAULT ((0)) FOR [TSA_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__SAN_C__5FBE24CE] DEFAULT ((0)) FOR [SAN_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__MAS_C__60B24907] DEFAULT ((0)) FOR [MAS_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__EGH_C__61A66D40] DEFAULT ((0)) FOR [EGH_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__PAR_C__629A9179] DEFAULT ((0)) FOR [PAR_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__PAS_C__638EB5B2] DEFAULT ((0)) FOR [PAS_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__DEY_C__6482D9EB] DEFAULT ((0)) FOR [DEY_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__SAM_C__6576FE24] DEFAULT ((0)) FOR [SAM_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__SAR_C__666B225D] DEFAULT ((0)) FOR [SAR_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__SIN_C__675F4696] DEFAULT ((0)) FOR [SIN_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANK__SHA_C__68536ACF] DEFAULT ((0)) FOR [SHA_C];
GO
ALTER TABLE [dbo].[TCOD_BANKS] ADD CONSTRAINT [DF__TCOD_BANKS__CRT__69F19A7E] DEFAULT (getdate()) FOR [CRT];
GO

CREATE TABLE [dbo].[TASKS](
    [IDNUM] [int] IDENTITY(1,1) NOT NULL,
    [GR] [int] NULL,
    [PERSONEL] [int] NULL,
    [TASK] [nvarchar](4000) NULL,
    [PERIORITY] [int] NULL,
    [STATUS] [int] NULL,
    [STDATE] [int] NULL,
    [STTIME] [int] NULL,
    [ENDATE] [int] NULL,
    [ENTIME] [int] NULL,
    [USERNAME] [nvarchar](50) NULL,
    [COMP_COD] [nvarchar](50) NOT NULL,
    [SUMTIME] [int] NULL,
    [pic] [image] NULL,
    [ss] [float] NULL,
    [skid] [int] NULL,
    [num] [bigint] NULL,
    [tg] [bigint] NULL,
    [CTIM] [datetime] NULL,
    [USERCO] [int] NULL,
    [SEE] [int] NULL,
    [SEET] [datetime] NULL,
    [CRT] [datetime] NULL,
    [UID] [int] NULL,
 CONSTRAINT [PK_TASKS] PRIMARY KEY CLUSTERED
(
    [IDNUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
GO
ALTER TABLE [dbo].[TASKS] ADD CONSTRAINT [DF_TASKS_PERIORITY] DEFAULT ((2)) FOR [PERIORITY];
GO
ALTER TABLE [dbo].[TASKS] ADD CONSTRAINT [DF_TASKS_STATUS] DEFAULT ((1)) FOR [STATUS];
GO
ALTER TABLE [dbo].[TASKS] ADD CONSTRAINT [DF_TASKS_CTIM] DEFAULT (getdate()) FOR [CTIM];
GO
ALTER TABLE [dbo].[TASKS] ADD CONSTRAINT [DF__TASKS__SEE__6BE95960] DEFAULT ((0)) FOR [SEE];
GO
ALTER TABLE [dbo].[TASKS] ADD CONSTRAINT [DF__TASKS__CRT__6CDD7D99] DEFAULT (getdate()) FOR [CRT];
GO

CREATE TABLE [dbo].[CUSTKIND](
	[CUST_COD] [int] NOT NULL,
	[CUSTKNAME] [nvarchar](50) NOT NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
 CONSTRAINT [aaaaaCUSTKIND_PK] PRIMARY KEY NONCLUSTERED 
(
	[CUST_COD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[DEPART](
	[DEPATMAN] [int] NOT NULL,
	[DEPNAME] [nvarchar](100) NOT NULL,
	[IDD] [int] IDENTITY(1,1) NOT NULL,
	[DEPART] [nvarchar](200) NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
	[PCODE] [nvarchar](10) NULL,
	[BBC] [nvarchar](50) NULL,
 CONSTRAINT [aaaaaDEPART_PK] PRIMARY KEY NONCLUSTERED 
(
	[DEPATMAN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[DETA_HES](
	[N_KOL] [int] NOT NULL,
	[NUMBER] [int] NOT NULL,
	[NAME] [nvarchar](100) NULL,
	[TOZIH] [nvarchar](40) NULL,
	[BED_BES] [float] NULL,
	[ADDRESS] [nvarchar](100) NULL,
	[TEL] [nvarchar](50) NULL,
	[CODE_E] [nvarchar](20) NULL,
	[USERCO] [int] NULL,
	[USER_NAME] [nvarchar](50) NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [aaaaaDETA_HES_PK] PRIMARY KEY NONCLUSTERED 
(
	[N_KOL] ASC,
	[NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[PRICE_ELAMIE](
	[PEPID] [int] NOT NULL,
	[PEPNAME] [nvarchar](250) NOT NULL,
	[PEPDATE] [int] NOT NULL,
	[TR_DATE] [datetime] NOT NULL,
	[USERNAME] [nvarchar](50) NOT NULL,
	[SGN1] [bit] NOT NULL,
	[SGN2] [bit] NOT NULL,
	[SGN3] [bit] NOT NULL,
	[SGN4] [bit] NOT NULL,
	[PEPDEPART] [int] NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
 CONSTRAINT [PK_PRICE_ELAMIE] PRIMARY KEY CLUSTERED 
(
	[PEPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[PRICE_ELAMIETF](
	[PEID] [int] NOT NULL,
	[PENAME] [nvarchar](250) NOT NULL,
	[PEDATE] [int] NOT NULL,
	[TR_DATE] [datetime] NOT NULL,
	[USERNAME] [nvarchar](50) NOT NULL,
	[SGN1] [bit] NOT NULL,
	[SGN2] [bit] NOT NULL,
	[SGN3] [bit] NOT NULL,
	[SGN4] [bit] NOT NULL,
	[PEPDEPART] [int] NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
 CONSTRAINT [PK_PRICE_ELAMIETF] PRIMARY KEY CLUSTERED 
(
	[PEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[PRICE_PAYNO](
	[PPID] [int] NOT NULL,
	[PPAME] [nvarchar](250) NOT NULL,
	[TR_DATE] [datetime] NOT NULL,
	[USERNAME] [nvarchar](50) NOT NULL,
	[MODAT] [int] NOT NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
 CONSTRAINT [PK_PRICE_PAYNO] PRIMARY KEY CLUSTERED 
(
	[PPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[SHIFT](
	[SHIFT_ID] [int] NOT NULL,
	[SHNAME] [nvarchar](20) NOT NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
 CONSTRAINT [aaaaaSHIFT_PK] PRIMARY KEY NONCLUSTERED 
(
	[SHIFT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TCOD_HESGROUP](
	[CODE] [float] NOT NULL,
	[NAMES] [nvarchar](50) NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
 CONSTRAINT [aaaaaTCOD_HESGROUP_PK] PRIMARY KEY NONCLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TCOD_HESKIND](
	[CODE] [float] NOT NULL,
	[NAMES] [nvarchar](32) NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
 CONSTRAINT [aaaaaTCOD_HESKIND_PK] PRIMARY KEY NONCLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TCOD_HESVAZ](
	[CODE] [float] NOT NULL,
	[NAMES] [nvarchar](32) NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
 CONSTRAINT [aaaaaTCOD_HESVAZ_PK] PRIMARY KEY NONCLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TDETA_HES](
	[N_KOL] [int] NOT NULL,
	[NUMBER] [int] NOT NULL,
	[TNUMBER] [int] NOT NULL,
	[NAME] [nvarchar](100) NULL,
	[TOZIH] [nvarchar](255) NULL,
	[BED_BES] [float] NULL,
	[ADDRESS] [nvarchar](100) NULL,
	[TEL] [nvarchar](50) NULL,
	[CODE_E] [nvarchar](20) NULL,
	[IDD] [int] IDENTITY(1,1) NOT NULL,
	[ECODE] [nvarchar](20) NULL,
	[PCODE] [nvarchar](10) NULL,
	[IYALAT] [nvarchar](20) NULL,
	[CITY] [nvarchar](20) NULL,
	[MCODEM] [nvarchar](20) NULL,
	[CUST_COD] [int] NULL,
	[MOBILE] [nvarchar](55) NULL,
	[ROUTE_NAME] [nvarchar](50) NULL,
	[Longitude] [float] NULL,
	[Latitude] [float] NULL,
	[OSTANID] [int] NULL,
	[SHAHRID] [int] NULL,
	[USERCO] [int] NULL,
	[USER_NAME] [nvarchar](50) NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
	[tob] [int] NULL,
 CONSTRAINT [PK_TDETA_HES] PRIMARY KEY CLUSTERED 
(
	[N_KOL] ASC,
	[NUMBER] ASC,
	[TNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_TDETA_HES_NAME] UNIQUE NONCLUSTERED 
(
	[N_KOL] ASC,
	[NUMBER] ASC,
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TOTA_HES](
	[NUMBER] [int] NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[NO_HES] [float] NULL,
	[M_D] [float] NULL,
	[GROUP] [float] NULL,
	[CRT] [datetime] NULL,
	[UID] [int] NULL,
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [aaaaaTOTA_HES_PK] PRIMARY KEY NONCLUSTERED 
(
	[NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTKIND] ADD  CONSTRAINT [DF__CUSTKIND__CRT__0B1D841F]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[DEPART] ADD  CONSTRAINT [DF__DEPART__CRT__5B6E70FD]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[DETA_HES] ADD  CONSTRAINT [DF__DETA_HES__N_KOL__15DA3E5D]  DEFAULT ((0)) FOR [N_KOL]
GO
ALTER TABLE [dbo].[DETA_HES] ADD  CONSTRAINT [DF__DETA_HES__NUMBER__16CE6296]  DEFAULT ((0)) FOR [NUMBER]
GO
ALTER TABLE [dbo].[DETA_HES] ADD  CONSTRAINT [DF__DETA_HES__CRT__67152DD3]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[PRICE_ELAMIE] ADD  CONSTRAINT [DF_PRICE_ELAMIE_SGN1]  DEFAULT ((0)) FOR [SGN1]
GO
ALTER TABLE [dbo].[PRICE_ELAMIE] ADD  CONSTRAINT [DF_PRICE_ELAMIE_SGN2]  DEFAULT ((0)) FOR [SGN2]
GO
ALTER TABLE [dbo].[PRICE_ELAMIE] ADD  CONSTRAINT [DF_PRICE_ELAMIE_SGN3]  DEFAULT ((0)) FOR [SGN3]
GO
ALTER TABLE [dbo].[PRICE_ELAMIE] ADD  CONSTRAINT [DF_PRICE_ELAMIE_SGN4]  DEFAULT ((0)) FOR [SGN4]
GO
ALTER TABLE [dbo].[PRICE_ELAMIE] ADD  CONSTRAINT [DF__PRICE_ELAMI__CRT__3A42875C]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[PRICE_ELAMIETF] ADD  CONSTRAINT [DF_PRICE_ELAMIETF_SGN1]  DEFAULT ((0)) FOR [SGN1]
GO
ALTER TABLE [dbo].[PRICE_ELAMIETF] ADD  CONSTRAINT [DF_PRICE_ELAMIETF_SGN2]  DEFAULT ((0)) FOR [SGN2]
GO
ALTER TABLE [dbo].[PRICE_ELAMIETF] ADD  CONSTRAINT [DF_PRICE_ELAMIETF_SGN3]  DEFAULT ((0)) FOR [SGN3]
GO
ALTER TABLE [dbo].[PRICE_ELAMIETF] ADD  CONSTRAINT [DF_PRICE_ELAMIETF_SGN4]  DEFAULT ((0)) FOR [SGN4]
GO
ALTER TABLE [dbo].[PRICE_ELAMIETF] ADD  CONSTRAINT [DF__PRICE_ELAMI__CRT__45B43A08]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[PRICE_PAYNO] ADD  CONSTRAINT [DF__PRICE_PAY__MODAT__41A3B202]  DEFAULT ((0)) FOR [MODAT]
GO
ALTER TABLE [dbo].[PRICE_PAYNO] ADD  CONSTRAINT [DF__PRICE_PAYNO__CRT__4A78EF25]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[SHIFT] ADD  CONSTRAINT [DF__SHIFT__CRT__3C2ACFCE]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[TCOD_HESGROUP] ADD  CONSTRAINT [DF__TCOD_HESGRO__CRT__02883E1E]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[TCOD_HESKIND] ADD  CONSTRAINT [DF__TCOD_HESKIN__CRT__7EB7AD3A]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[TCOD_HESVAZ] ADD  CONSTRAINT [DF__TCOD_HESVAZ__CRT__780AAFAB]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[TDETA_HES] ADD  CONSTRAINT [DF__TDETA_HES__CODE___7DCDAAA2]  DEFAULT ('0') FOR [CODE_E]
GO
ALTER TABLE [dbo].[TDETA_HES] ADD  CONSTRAINT [DF__TDETA_HES__CRT__4A43E4FB]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[TDETA_HES] ADD  CONSTRAINT [DF__TDETA_HES__tob__20389C96]  DEFAULT ((2)) FOR [tob]
GO
ALTER TABLE [dbo].[TOTA_HES] ADD  CONSTRAINT [DF__TOTA_HES__NUMBER__075714DC]  DEFAULT ((0)) FOR [NUMBER]
GO
ALTER TABLE [dbo].[TOTA_HES] ADD  CONSTRAINT [DF__TOTA_HES__NO_HES__084B3915]  DEFAULT ((0)) FOR [NO_HES]
GO
ALTER TABLE [dbo].[TOTA_HES] ADD  CONSTRAINT [DF__TOTA_HES__M_D__093F5D4E]  DEFAULT ((0)) FOR [M_D]
GO
ALTER TABLE [dbo].[TOTA_HES] ADD  CONSTRAINT [DF__TOTA_HES__GROUP__0A338187]  DEFAULT ((0)) FOR [GROUP]
GO
ALTER TABLE [dbo].[TOTA_HES] ADD  CONSTRAINT [DF__TOTA_HES__CRT__40BA7AC1]  DEFAULT (getdate()) FOR [CRT]
GO
ALTER TABLE [dbo].[DETA_HES]  WITH NOCHECK ADD  CONSTRAINT [DETA_HES_FK00] FOREIGN KEY([N_KOL])
REFERENCES [dbo].[TOTA_HES] ([NUMBER])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[DETA_HES] CHECK CONSTRAINT [DETA_HES_FK00]
GO
ALTER TABLE [dbo].[TDETA_HES]  WITH NOCHECK ADD  CONSTRAINT [FK_TDETA_HES_DETA_HES] FOREIGN KEY([N_KOL], [NUMBER])
REFERENCES [dbo].[DETA_HES] ([N_KOL], [NUMBER])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TDETA_HES] CHECK CONSTRAINT [FK_TDETA_HES_DETA_HES]
GO
ALTER TABLE [dbo].[TOTA_HES]  WITH NOCHECK ADD  CONSTRAINT [TOTA_HES_FK00] FOREIGN KEY([NO_HES])
REFERENCES [dbo].[TCOD_HESKIND] ([CODE])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TOTA_HES] CHECK CONSTRAINT [TOTA_HES_FK00]
GO
ALTER TABLE [dbo].[TOTA_HES]  WITH NOCHECK ADD  CONSTRAINT [TOTA_HES_FK01] FOREIGN KEY([M_D])
REFERENCES [dbo].[TCOD_HESVAZ] ([CODE])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TOTA_HES] CHECK CONSTRAINT [TOTA_HES_FK01]
GO
ALTER TABLE [dbo].[TOTA_HES]  WITH NOCHECK ADD  CONSTRAINT [TOTA_HES_FK02] FOREIGN KEY([GROUP])
REFERENCES [dbo].[TCOD_HESGROUP] ([CODE])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TOTA_HES] CHECK CONSTRAINT [TOTA_HES_FK02]
GO


-- Fail fast if any required legacy table was not created.
IF OBJECT_ID(N'dbo.TCOD_BANKS', N'U') IS NULL THROW 53000, 'Missing bootstrap table dbo.TCOD_BANKS', 1;
IF OBJECT_ID(N'dbo.TASKS', N'U') IS NULL THROW 53000, 'Missing bootstrap table dbo.TASKS', 1;
IF OBJECT_ID(N'dbo.CUSTKIND', N'U') IS NULL THROW 53000, 'Missing bootstrap table dbo.CUSTKIND', 1;
IF OBJECT_ID(N'dbo.DEPART', N'U') IS NULL THROW 53000, 'Missing bootstrap table dbo.DEPART', 1;
IF OBJECT_ID(N'dbo.DETA_HES', N'U') IS NULL THROW 53000, 'Missing bootstrap table dbo.DETA_HES', 1;
IF OBJECT_ID(N'dbo.PRICE_ELAMIE', N'U') IS NULL THROW 53000, 'Missing bootstrap table dbo.PRICE_ELAMIE', 1;
IF OBJECT_ID(N'dbo.PRICE_ELAMIETF', N'U') IS NULL THROW 53000, 'Missing bootstrap table dbo.PRICE_ELAMIETF', 1;
IF OBJECT_ID(N'dbo.PRICE_PAYNO', N'U') IS NULL THROW 53000, 'Missing bootstrap table dbo.PRICE_PAYNO', 1;
IF OBJECT_ID(N'dbo.SHIFT', N'U') IS NULL THROW 53000, 'Missing bootstrap table dbo.SHIFT', 1;
IF OBJECT_ID(N'dbo.TCOD_HESGROUP', N'U') IS NULL THROW 53000, 'Missing bootstrap table dbo.TCOD_HESGROUP', 1;
IF OBJECT_ID(N'dbo.TCOD_HESKIND', N'U') IS NULL THROW 53000, 'Missing bootstrap table dbo.TCOD_HESKIND', 1;
IF OBJECT_ID(N'dbo.TCOD_HESVAZ', N'U') IS NULL THROW 53000, 'Missing bootstrap table dbo.TCOD_HESVAZ', 1;
IF OBJECT_ID(N'dbo.TDETA_HES', N'U') IS NULL THROW 53000, 'Missing bootstrap table dbo.TDETA_HES', 1;
IF OBJECT_ID(N'dbo.TOTA_HES', N'U') IS NULL THROW 53000, 'Missing bootstrap table dbo.TOTA_HES', 1;
GO
PRINT N'Legacy dependency schema created successfully.';
GO
