/* =============================================================================
   هم‌ترازکردن دیتابیس تست با ScriptSqly.cs
   =============================================================================
   منبع حقیقتِ ساختار دیتابیس، Server/Info/ScriptSqly.cs است (همان چیزی که روی
   دیتابیس مشتری اجرا می‌شود). ولی schema.sql — که دیتابیس تست از آن ساخته
   می‌شود — یک عکسِ قدیمی‌تر است و ستون‌هایی که در نسخه‌های بعدیِ موتور اضافه
   شده‌اند را ندارد.

   نتیجه‌ی عملی‌اش این بود که دیتابیس تست ده‌ها ستون از تولید عقب بود و هر
   آزمونی که واقعاً حکم ثبت می‌کرد یا حقوق محاسبه می‌کرد با «Invalid column
   name» شکست می‌خورد — یعنی زنجیره‌ی اصلی کسب‌وکار اصلاً قابل آزمودن نبود.

   این فایل دقیقاً همان ALTERهای گاردشده‌ی ScriptSqly.cs است که استخراج شده تا
   جدا اجرا شود؛ همان قراردادی که pay2_acl_migration.sql دارد.

   هر دستور دو گارد دارد: وجودِ جدول و نبودِ ستون. پس هم idempotent است و هم
   روی جدول‌هایی که اصلاً در schema.sql نیستند (مثل PAY2_RUN_EMP_SNAPSHOT و
   جدول‌های SANOVAT) بی‌صدا رد می‌شود — آن‌ها برای آزمون‌های فعلی لازم نیستند.

   اگر روزی ستونی به ScriptSqly.cs اضافه شد، همین‌جا هم باید اضافه شود.
   ============================================================================= */
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID(N'dbo.PAY2_DECREE_LINE', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_DECREE_LINE','NOMINAL_AMOUNT_OV') IS NULL ALTER TABLE dbo.PAY2_DECREE_LINE ADD NOMINAL_AMOUNT_OV DECIMAL(18,2) NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_DECREE_LINE', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_DECREE_LINE','OFFICIAL_AMOUNT_OV') IS NULL ALTER TABLE dbo.PAY2_DECREE_LINE ADD OFFICIAL_AMOUNT_OV DECIMAL(18,2) NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_DETAIL', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_DETAIL','NOMINAL_AMOUNT') IS NULL ALTER TABLE dbo.PAY2_RUN_DETAIL ADD NOMINAL_AMOUNT BIGINT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_DETAIL', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_DETAIL','ITEM_CODE_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_DETAIL ADD ITEM_CODE_SNAP NVARCHAR(30) NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_DETAIL', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_DETAIL','ITEM_NAME_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_DETAIL ADD ITEM_NAME_SNAP NVARCHAR(200) NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_DETAIL', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_DETAIL','CALC_BASIS_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_DETAIL ADD CALC_BASIS_SNAP TINYINT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_DETAIL', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_DETAIL','ITEM_TYPE_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_DETAIL ADD ITEM_TYPE_SNAP TINYINT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_DETAIL', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_DETAIL','INS_SUBJECT_AMOUNT') IS NULL ALTER TABLE dbo.PAY2_RUN_DETAIL ADD INS_SUBJECT_AMOUNT BIGINT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_DETAIL', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_DETAIL','TAX_SUBJECT_AMOUNT') IS NULL ALTER TABLE dbo.PAY2_RUN_DETAIL ADD TAX_SUBJECT_AMOUNT BIGINT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_ATTENDANCE', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_ATTENDANCE','SHORTAGE_H') IS NULL ALTER TABLE dbo.PAY2_ATTENDANCE ADD SHORTAGE_H DECIMAL(6,2) NOT NULL CONSTRAINT DF_ATT_SHRT DEFAULT(0);
GO
IF OBJECT_ID(N'dbo.PAY2_RUN', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN','PAYROLL_ENGINE_VERSION') IS NULL ALTER TABLE dbo.PAY2_RUN ADD PAYROLL_ENGINE_VERSION SMALLINT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN','WS_ID_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN ADD WS_ID_SNAP INT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_LINE', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_LINE','NOMINAL_GROSS') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD NOMINAL_GROSS BIGINT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_LINE', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_LINE','NOMINAL_DAYS') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD NOMINAL_DAYS DECIMAL(5,2) NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_LINE', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_LINE','INS_EMPLOYER_BASE') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD INS_EMPLOYER_BASE BIGINT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_LINE', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_LINE','INS_UNEMPLOYMENT') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD INS_UNEMPLOYMENT BIGINT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_LINE', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_LINE','ROUNDING_ADJ') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD ROUNDING_ADJ BIGINT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_LINE', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_LINE','HIRE_DATE_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD HIRE_DATE_SNAP BIGINT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_LINE', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_LINE','FIRE_DATE_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD FIRE_DATE_SNAP BIGINT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_EMP_SNAPSHOT', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_EMP_SNAPSHOT','IS_MANAGER_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_EMP_SNAPSHOT ADD IS_MANAGER_SNAP BIT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_EMP_SNAPSHOT', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_EMP_SNAPSHOT','IS_JANBAZ_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_EMP_SNAPSHOT ADD IS_JANBAZ_SNAP BIT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_EMP_SNAPSHOT', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_EMP_SNAPSHOT','REGION_DEPRIVATION_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_EMP_SNAPSHOT ADD REGION_DEPRIVATION_SNAP TINYINT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_RUN_EMP_SNAPSHOT', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_RUN_EMP_SNAPSHOT','ACC_T_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_EMP_SNAPSHOT ADD ACC_T_SNAP NVARCHAR(50) NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_SANOVAT_MIGRATION_INPUT', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_INPUT','SOURCE_RAIL') IS NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_INPUT ADD SOURCE_RAIL NVARCHAR(10) NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_SANOVAT_MIGRATION_INPUT', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_INPUT','NOMINAL_SENIORITY_DAILY') IS NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_INPUT ADD NOMINAL_SENIORITY_DAILY DECIMAL(18,2) NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_SANOVAT_MIGRATION_INPUT', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_INPUT','OFFICIAL_SENIORITY_DAILY') IS NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_INPUT ADD OFFICIAL_SENIORITY_DAILY DECIMAL(18,2) NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_SANOVAT_MIGRATION_LOG', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_LOG','NEW_DEC_ID') IS NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_LOG ADD NEW_DEC_ID INT NULL, EFFECTIVE_FROM BIGINT NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_SANOVAT_MIGRATION_LOG', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_LOG','SOURCE_RAIL') IS NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_LOG ADD SOURCE_RAIL NVARCHAR(10) NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_SANOVAT_MIGRATION_LOG', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_LOG','NOMINAL_BASE_BEFORE') IS NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_LOG ADD NOMINAL_BASE_BEFORE DECIMAL(18,2) NULL, NOMINAL_SENIORITY DECIMAL(18,2) NULL, NOMINAL_BASE_AFTER DECIMAL(18,2) NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_SANOVAT_MIGRATION_LOG', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_LOG','OFFICIAL_BASE_BEFORE') IS NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_LOG ADD OFFICIAL_BASE_BEFORE DECIMAL(18,2) NULL, OFFICIAL_SENIORITY DECIMAL(18,2) NULL, OFFICIAL_BASE_AFTER DECIMAL(18,2) NULL;
GO
IF OBJECT_ID(N'dbo.PAY2_INS_NON_SUBJECT_OPTIN_LOG', N'U') IS NOT NULL AND COL_LENGTH('dbo.PAY2_INS_NON_SUBJECT_OPTIN_LOG','EFFECTIVE_FROM') IS NULL ALTER TABLE dbo.PAY2_INS_NON_SUBJECT_OPTIN_LOG ADD EFFECTIVE_FROM BIGINT NOT NULL CONSTRAINT DF_PAY2_INS_OPTIN_EFF DEFAULT(0) WITH VALUES;
GO
/* ── ویوهایی که schema.sql استفاده می‌کند ولی نمی‌سازد ────────────────────
   schema.sql داخل رویه‌های خودش از V_PAY2_LOAN_BALANCE می‌خواند ولی هیچ‌جا
   آن را CREATE نمی‌کند؛ یعنی هر محاسبه‌ی حقوقی روی دیتابیس تست با
   «Invalid object name» می‌افتاد. تعریف زیر عیناً از ScriptSqly.cs است. */
CREATE OR ALTER VIEW [dbo].[V_PAY2_LOAN_BALANCE] AS
SELECT
    L.EMP_ID,
    L.LOAN_ID,
    L.AMOUNT                            AS TOTAL_AMOUNT,
    L.PAID_INST * L.INSTALLMENT         AS TOTAL_PAID,
    L.AMOUNT - L.PAID_INST*L.INSTALLMENT AS BALANCE,
    L.INSTALLMENT                       AS NEXT_INSTALLMENT,
    (L.TOTAL_INST - L.PAID_INST)        AS REMAINING_INST
FROM PAY2_LOAN L
WHERE L.IS_ACTIVE = 1 AND L.PAID_INST < L.TOTAL_INST;
GO

PRINT N'✅ ساختار دیتابیس تست با ScriptSqly.cs هم‌تراز شد.';
GO
