namespace Safir.Server.Services;

/// <summary>
/// Reads payroll report values exclusively from the effective snapshots of a run.
/// Current item configuration is used only to identify legacy rows created before
/// snapshot columns existed; effective insurance/tax flags always come from RUN_DETAIL.
/// </summary>
internal static class Pay2PayrollSnapshotQuery
{
    internal const string Sql = @"
WITH Detail AS
(
    SELECT D.RUN_ID, D.EMP_ID,
           COALESCE(D.ITEM_CODE_SNAP, I.ITEM_CODE) AS ITEM_CODE,
           COALESCE(D.ITEM_TYPE_SNAP, I.ITEM_TYPE) AS ITEM_TYPE,
           COALESCE(D.NOMINAL_AMOUNT, D.AMOUNT) AS NOMINAL_AMOUNT,
           D.INS_SUBJECT, D.TAX_SUBJECT
    FROM dbo.PAY2_RUN_DETAIL D WITH (NOLOCK)
    INNER JOIN dbo.PAY2_ITEM_DEF I WITH (NOLOCK) ON I.ITEM_ID = D.ITEM_ID
    WHERE D.RUN_ID = @runId
), Agg AS
(
    SELECT EMP_ID,
       SUM(CASE WHEN ITEM_CODE='BASE_SAL' THEN NOMINAL_AMOUNT ELSE 0 END) AS BASE_WAGE_MONTHLY,
       SUM(CASE WHEN ITEM_CODE='SANOVAT_PAYE' THEN NOMINAL_AMOUNT ELSE 0 END) AS SENIORITY_MONTHLY,
       SUM(CASE WHEN ITEM_CODE IN ('HOME','GROCERY') AND INS_SUBJECT=1 THEN NOMINAL_AMOUNT ELSE 0 END) AS HOME_GROCERY_BENEFITS,
       SUM(CASE WHEN ITEM_CODE='FAMILY_ALLOW' AND INS_SUBJECT=1 THEN NOMINAL_AMOUNT ELSE 0 END) AS MARITAL_ALLOWANCE,
       SUM(CASE WHEN INS_SUBJECT=1 AND ITEM_TYPE IN (1,2)
                 AND ITEM_CODE NOT IN ('BASE_SAL','BASE_SAL_B','SANOVAT_PAYE','HOME','GROCERY','FAMILY_ALLOW')
                THEN NOMINAL_AMOUNT ELSE 0 END) AS OTHER_SUBJECT_ITEMS,
       SUM(CASE WHEN ITEM_TYPE IN (1,2) AND ITEM_CODE <> 'BASE_SAL_B' THEN NOMINAL_AMOUNT ELSE 0 END) AS NOMINAL_GROSS
    FROM Detail GROUP BY EMP_ID
)
SELECT RL.EMP_ID, E.FIRST_NAME, E.LAST_NAME,
       E.LAST_NAME + N' ' + E.FIRST_NAME AS FULL_NAME,
       E.NATIONAL_CODE, E.INS_CODE, E.FATHER_NAME, E.ID_NUMBER, E.BIRTH_PLACE,
       E.BIRTH_DATE, E.GENDER, E.NATIONALITY, E.MARITAL, E.MOBILE, E.INS_TYPE, E.TAX_EXEMPT,
       J.JOB_CODE, J.JOB_NAME, P.PERIOD_DATE,
       COALESCE(RL.NOMINAL_DAYS, A.DAYS, RL.WORK_DAYS) AS INSURANCE_DAYS,
       COALESCE(RL.HIRE_DATE_SNAP, E.HIRE_DATE) AS HIRE_DATE,
       COALESCE(RL.FIRE_DATE_SNAP, E.FIRE_DATE) AS FIRE_DATE,
       ISNULL(G.BASE_WAGE_MONTHLY,0) AS BASE_WAGE_MONTHLY,
       ISNULL(G.SENIORITY_MONTHLY,0) AS SENIORITY_MONTHLY,
       ISNULL(G.HOME_GROCERY_BENEFITS,0) + ISNULL(G.MARITAL_ALLOWANCE,0) + ISNULL(G.OTHER_SUBJECT_ITEMS,0) AS OTHER_SUBJECT_BENEFITS,
       ISNULL(G.HOME_GROCERY_BENEFITS,0) + ISNULL(G.OTHER_SUBJECT_ITEMS,0) AS DBF_GENERAL_BENEFITS,
       ISNULL(G.MARITAL_ALLOWANCE,0) AS MARITAL_ALLOWANCE,
       ISNULL(G.NOMINAL_GROSS, COALESCE(RL.NOMINAL_GROSS,RL.GROSS_PAY)) AS NOMINAL_GROSS,
       RL.INS_BASE, RL.INS_WORKER, RL.INS_EMPLOYER, RL.TAX_BASE, RL.TAX_AMOUNT,
       RL.LOAN_DED, RL.ADVANCE_DED, RL.OTHER_DED, RL.TOTAL_DED,
       ISNULL(RL.ROUNDING_ADJ,0) AS ROUNDING_ADJ,
       ISNULL(G.NOMINAL_GROSS, COALESCE(RL.NOMINAL_GROSS,RL.GROSS_PAY))
         - RL.TOTAL_DED + ISNULL(RL.ROUNDING_ADJ,0) AS NOMINAL_NET_PAYABLE
FROM dbo.PAY2_RUN_LINE RL WITH (NOLOCK)
INNER JOIN dbo.PAY2_RUN R WITH (NOLOCK) ON R.RUN_ID=RL.RUN_ID
INNER JOIN dbo.PAY2_PERIOD P WITH (NOLOCK) ON P.PER_ID=R.PER_ID
INNER JOIN dbo.PAY2_EMPLOYEE E WITH (NOLOCK) ON E.EMP_ID=RL.EMP_ID
LEFT JOIN dbo.PAY2_ATTENDANCE A WITH (NOLOCK) ON A.PER_ID=R.PER_ID AND A.EMP_ID=RL.EMP_ID
LEFT JOIN dbo.PAY2_JOB J WITH (NOLOCK) ON J.JOB_ID=E.JOB_ID
LEFT JOIN Agg G ON G.EMP_ID=RL.EMP_ID
WHERE RL.RUN_ID=@runId
ORDER BY E.LAST_NAME,E.FIRST_NAME";
}
