namespace Safir.Server.Services;

/// <summary>
/// Reads payroll report values exclusively from the effective snapshots of a run.
/// Legal output never falls back to current item configuration: an incomplete
/// historical snapshot is rejected by HAS_COMPLETE_NOMINAL_SNAPSHOT.
/// </summary>
internal static class Pay2PayrollSnapshotQuery
{
    internal const string Sql = @"
WITH Detail AS
(
    SELECT D.RUN_ID, D.EMP_ID,
           D.ITEM_CODE_SNAP AS ITEM_CODE, D.ITEM_NAME_SNAP AS ITEM_NAME,
           D.ITEM_TYPE_SNAP AS ITEM_TYPE,
           D.NOMINAL_AMOUNT AS NOMINAL_AMOUNT,
           D.NOMINAL_AMOUNT AS NOMINAL_SNAPSHOT,
           D.INS_SUBJECT_AMOUNT, D.TAX_SUBJECT_AMOUNT, D.INS_SUBJECT, D.TAX_SUBJECT
    FROM dbo.PAY2_RUN_DETAIL D
    WHERE D.RUN_ID = @runId
), Agg AS
(
    SELECT EMP_ID,
       SUM(CASE WHEN ITEM_CODE='BASE_SAL' THEN NOMINAL_AMOUNT ELSE 0 END) AS BASE_WAGE_MONTHLY,
       SUM(CASE WHEN ITEM_CODE='SANOVAT_PAYE' THEN NOMINAL_AMOUNT ELSE 0 END) AS SENIORITY_MONTHLY,
       SUM(CASE WHEN ITEM_CODE IN('BASE_SAL','SANOVAT_PAYE') THEN INS_SUBJECT_AMOUNT ELSE 0 END) AS INSURANCE_WAGE_MONTHLY,
       SUM(CASE WHEN ITEM_CODE IN('BASE_SAL','SANOVAT_PAYE') THEN TAX_SUBJECT_AMOUNT ELSE 0 END) AS TAXABLE_WAGE_MONTHLY,
       SUM(CASE WHEN ITEM_CODE IN('HOME','GROCERY','FAMILY_ALLOW') THEN INS_SUBJECT_AMOUNT ELSE 0 END) AS DIRECT_INSURANCE_BENEFITS,
       SUM(CASE WHEN ITEM_CODE IN ('HOME','GROCERY') THEN NOMINAL_AMOUNT ELSE 0 END) AS HOME_GROCERY_BENEFITS,
       SUM(CASE WHEN ITEM_CODE='FAMILY_ALLOW' THEN NOMINAL_AMOUNT ELSE 0 END) AS MARITAL_ALLOWANCE,
       SUM(CASE WHEN ITEM_CODE IN ('HOME','GROCERY') THEN INS_SUBJECT_AMOUNT ELSE 0 END) AS INS_HOME_GROCERY_BENEFITS,
       SUM(CASE WHEN ITEM_CODE='FAMILY_ALLOW' THEN INS_SUBJECT_AMOUNT ELSE 0 END) AS INS_MARITAL_ALLOWANCE,
       SUM(CASE WHEN ITEM_TYPE IN (1,2)
                 AND ITEM_CODE NOT IN ('BASE_SAL','BASE_SAL_B','SANOVAT_PAYE','HOME','GROCERY','FAMILY_ALLOW')
                THEN INS_SUBJECT_AMOUNT ELSE 0 END) AS OTHER_INSURANCE_SUBJECT_ITEMS,
       SUM(CASE WHEN ITEM_TYPE IN (1,2)
                 AND ITEM_CODE NOT IN ('BASE_SAL','BASE_SAL_B','SANOVAT_PAYE')
                THEN TAX_SUBJECT_AMOUNT ELSE 0 END) AS OTHER_TAXABLE_ITEMS,
       SUM(CASE WHEN ITEM_TYPE IN (1,2) AND ITEM_CODE <> 'BASE_SAL_B' THEN NOMINAL_AMOUNT ELSE 0 END) AS NOMINAL_GROSS
    FROM Detail GROUP BY EMP_ID
)
SELECT RL.EMP_ID, ES.EMP_CODE, ES.FIRST_NAME, ES.LAST_NAME,
       ES.LAST_NAME + N' ' + ES.FIRST_NAME AS FULL_NAME,
       ES.NATIONAL_CODE, ES.INS_CODE, ES.FATHER_NAME, ES.ID_NUMBER, ES.BIRTH_PLACE,
       ES.BIRTH_DATE, ES.GENDER, ES.NATIONALITY_SNAP AS NATIONALITY,
       ES.MARITAL_SNAP AS MARITAL, ES.MOBILE, ES.INS_TYPE_SNAP AS INS_TYPE,
       ES.TAX_EXEMPT_SNAP AS TAX_EXEMPT,
       ES.JOB_CODE_SNAP AS JOB_CODE, ES.JOB_NAME_SNAP AS JOB_NAME, P.PERIOD_DATE,
       RL.NOMINAL_DAYS AS INSURANCE_DAYS,
       ES.HIRE_DATE_SNAP AS HIRE_DATE,
       ES.FIRE_DATE_SNAP AS FIRE_DATE,
       ISNULL(G.BASE_WAGE_MONTHLY,0) AS BASE_WAGE_MONTHLY,
       ISNULL(G.SENIORITY_MONTHLY,0) AS SENIORITY_MONTHLY,
       ISNULL(G.INSURANCE_WAGE_MONTHLY,0) AS INSURANCE_WAGE_MONTHLY,
       ISNULL(G.TAXABLE_WAGE_MONTHLY,0) AS TAXABLE_WAGE_MONTHLY,
       ISNULL(G.DIRECT_INSURANCE_BENEFITS,0) AS DIRECT_INSURANCE_BENEFITS,
       ISNULL(G.INS_HOME_GROCERY_BENEFITS,0) + ISNULL(G.INS_MARITAL_ALLOWANCE,0) AS DISPLAY_OTHER_BENEFITS,
       ISNULL(G.OTHER_INSURANCE_SUBJECT_ITEMS,0) AS OTHER_INSURANCE_SUBJECT_ITEMS,
       ISNULL(G.OTHER_TAXABLE_ITEMS,0) AS OTHER_TAXABLE_ITEMS,
       ISNULL(G.INS_HOME_GROCERY_BENEFITS,0) + ISNULL(G.OTHER_INSURANCE_SUBJECT_ITEMS,0) AS DBF_GENERAL_BENEFITS,
       ISNULL(G.INS_MARITAL_ALLOWANCE,0) AS MARITAL_ALLOWANCE,
       RL.NOMINAL_GROSS AS NOMINAL_GROSS,
       RL.INS_BASE, RL.INS_WORKER, RL.INS_EMPLOYER, RL.INS_EMPLOYER_BASE, RL.INS_UNEMPLOYMENT, RL.TAX_BASE, RL.TAX_AMOUNT,
       RL.LOAN_DED, RL.ADVANCE_DED, RL.OTHER_DED, RL.TOTAL_DED,
       CASE WHEN EXISTS(SELECT 1 FROM Detail X WHERE X.EMP_ID=RL.EMP_ID AND X.ITEM_CODE='BASE_SAL' AND X.NOMINAL_SNAPSHOT IS NOT NULL) THEN CAST(1 AS bit) ELSE CAST(0 AS bit) END AS HAS_NOMINAL_RAIL,
       CASE WHEN RL.NOMINAL_DAYS IS NOT NULL AND RL.NOMINAL_GROSS IS NOT NULL
                  AND NOT EXISTS(SELECT 1 FROM Detail X WHERE X.EMP_ID=RL.EMP_ID AND
                       (X.NOMINAL_SNAPSHOT IS NULL OR X.ITEM_CODE IS NULL OR X.ITEM_NAME IS NULL OR X.ITEM_TYPE IS NULL OR X.INS_SUBJECT_AMOUNT IS NULL OR X.TAX_SUBJECT_AMOUNT IS NULL
                        OR (X.ITEM_CODE='BASE_SAL_B' AND (X.INS_SUBJECT_AMOUNT<>0 OR X.TAX_SUBJECT_AMOUNT<>0))))
            THEN CAST(1 AS bit) ELSE CAST(0 AS bit) END AS HAS_COMPLETE_NOMINAL_SNAPSHOT,
       CASE WHEN RL.INS_EMPLOYER_BASE IS NOT NULL AND RL.INS_UNEMPLOYMENT IS NOT NULL THEN CAST(1 AS bit) ELSE CAST(0 AS bit) END AS PREMIUM_SNAPSHOT_AVAILABLE,
       CASE WHEN ES.RUN_ID IS NOT NULL THEN CAST(1 AS bit) ELSE CAST(0 AS bit) END AS HAS_COMPLETE_EMP_SNAPSHOT,
       ISNULL(RL.ROUNDING_ADJ,0) AS ROUNDING_ADJ,
       RL.NOMINAL_GROSS - RL.TOTAL_DED AS NOMINAL_NET_PAYABLE
FROM dbo.PAY2_RUN_LINE RL
INNER JOIN dbo.PAY2_RUN R ON R.RUN_ID=RL.RUN_ID
INNER JOIN dbo.PAY2_PERIOD P ON P.PER_ID=R.PER_ID
LEFT JOIN dbo.PAY2_RUN_EMP_SNAPSHOT ES ON ES.RUN_ID=RL.RUN_ID AND ES.EMP_ID=RL.EMP_ID
LEFT JOIN Agg G ON G.EMP_ID=RL.EMP_ID
WHERE RL.RUN_ID=@runId
ORDER BY ES.LAST_NAME,ES.FIRST_NAME";
}
