-- Migration 009: افزودن تنظیمات حق شیفت به تفکیک کارگاه و پرسنل

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PAY2_WORKSHOP') AND name = 'SHIFT_MODE')
BEGIN
    ALTER TABLE [dbo].[PAY2_WORKSHOP] ADD [SHIFT_MODE] NVARCHAR(10) NULL;
    ALTER TABLE [dbo].[PAY2_WORKSHOP] ADD CONSTRAINT [CK_WS_SHIFT_MODE] CHECK ([SHIFT_MODE] IN ('PCT','FIXED'));
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PAY2_DECREE') AND name = 'SHIFT_MODE')
BEGIN
    ALTER TABLE [dbo].[PAY2_DECREE] ADD [SHIFT_MODE] NVARCHAR(10) NULL;
    ALTER TABLE [dbo].[PAY2_DECREE] ADD CONSTRAINT [CK_DEC_SHIFT_MODE] CHECK ([SHIFT_MODE] IN ('PCT','FIXED'));
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PAY2_DECREE_LINE') AND name = 'SHIFT_MODE_OV')
BEGIN
    ALTER TABLE [dbo].[PAY2_DECREE_LINE] ADD [SHIFT_MODE_OV] NVARCHAR(10) NULL;
    ALTER TABLE [dbo].[PAY2_DECREE_LINE] ADD CONSTRAINT [CK_DL_SHIFT_MODE_OV] CHECK ([SHIFT_MODE_OV] IN ('PCT','FIXED'));
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PAY2_ITEM_TMPL_LINE') AND name = 'SHIFT_MODE_OV')
BEGIN
    ALTER TABLE [dbo].[PAY2_ITEM_TMPL_LINE] ADD [SHIFT_MODE_OV] NVARCHAR(10) NULL;
    ALTER TABLE [dbo].[PAY2_ITEM_TMPL_LINE] ADD CONSTRAINT [CK_TL_SHIFT_MODE_OV] CHECK ([SHIFT_MODE_OV] IN ('PCT','FIXED'));
END
GO
