-- Migration 010: Fix configurations for Shift Allowance and Nominal Base Salary
-- Issue 1: Shift Allowance should not be subject to insurance.
UPDATE [dbo].[PAY2_ITEM_DEF]
SET [INS_SUBJECT] = 0
WHERE [ITEM_CODE] = 'SHIFT' AND [INS_SUBJECT] = 1;

-- Issue 3/4: Nominal Base Salary (BASE_SAL) and general allowances should evaluate based on Nominal Days (DAYS) instead of Official Days (DAYSB).
-- PAY_BASE_DAYS = 1 means it uses @DAYS (Nominal).
UPDATE [dbo].[PAY2_ITEM_DEF]
SET [PAY_BASE_DAYS] = 1
WHERE [ITEM_CODE] IN ('BASE_SAL', 'HOME', 'CHILDREN', 'FAMILY_ALLOW', 'ATTRACT', 'GROCERY', 'HARD_COND', 'OTHER_FIX') AND [PAY_BASE_DAYS] = 2;

GO

CREATE OR ALTER PROCEDURE [dbo].[SP_PAY2_CALC_RUN]
    @WS_ID       INT,
    @PER_ID      INT,
    @PAYROLL_N_S FLOAT,
    @CALC_BY     INT          = NULL,
    @IS_RERUN    BIT          = 0,
    @NEW_RUN_ID  INT          OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET ANSI_WARNINGS OFF;

    -- گام ۱ — بارگذاری تنظیمات
    DECLARE
        @MONTH_DAYS_MODE   NVARCHAR(10), @MONTH_DAYS        TINYINT,
        @OT_NORMAL_MULT    DECIMAL(6,4), @OT_HOLIDAY_MULT   DECIMAL(6,4),
        @OT_HOUR_BASE      DECIMAL(6,4), @SHIFT_MODE        NVARCHAR(10),
        @ROUND_MODE        INT,          @INS_WORKER_RATE   DECIMAL(6,4),
        @INS_EMPLOYER_RATE DECIMAL(6,4), @INS_UNEMP_RATE    DECIMAL(6,4),
        @INS_CEILING_APPLY BIT,          @INS_CEILING       BIGINT,
        @TAX_YEAR          SMALLINT,     @TAX_EXEMPT        BIGINT,
        @TAX_DEDUCT_INS    BIT,          @TAX_DEP_APPLY     BIT,
        @ADV_ENABLED       BIT,          @PERIOD_DATE       BIGINT,
        @PERIOD_MONTH      INT,          @PERIOD_YEAR       INT,
        @MONTHLY_PRORATE   BIT;

    SELECT
        @MONTH_DAYS_MODE   = ISNULL(MAX(CASE WHEN CFG_KEY='MONTH_DAYS_MODE'    THEN CFG_VALUE END), '30'),
        @OT_NORMAL_MULT    = ISNULL(MAX(CASE WHEN CFG_KEY='OT_NORMAL_MULT'     THEN CAST(CFG_VALUE AS DECIMAL(6,4)) END), 1.40),
        @OT_HOLIDAY_MULT   = ISNULL(MAX(CASE WHEN CFG_KEY='OT_HOLIDAY_MULT'    THEN CAST(CFG_VALUE AS DECIMAL(6,4)) END), 1.40),
        @OT_HOUR_BASE      = ISNULL(MAX(CASE WHEN CFG_KEY='OT_HOUR_BASE'       THEN CAST(CFG_VALUE AS DECIMAL(6,4)) END), 7.33),
        @SHIFT_MODE        = ISNULL(MAX(CASE WHEN CFG_KEY='SHIFT_MODE'         THEN CFG_VALUE END), 'PCT'),
        @ROUND_MODE        = ISNULL(MAX(CASE WHEN CFG_KEY='ROUND_MODE'         THEN CAST(CFG_VALUE AS INT) END), 1),
        @INS_WORKER_RATE   = ISNULL(MAX(CASE WHEN CFG_KEY='INS_WORKER_RATE'    THEN CAST(CFG_VALUE AS DECIMAL(6,4)) END) / 100.0, 0.07),
        @INS_EMPLOYER_RATE = ISNULL(MAX(CASE WHEN CFG_KEY='INS_EMPLOYER_RATE'  THEN CAST(CFG_VALUE AS DECIMAL(6,4)) END) / 100.0, 0.20),
        @INS_UNEMP_RATE    = ISNULL(MAX(CASE WHEN CFG_KEY='INS_UNEMP_RATE'     THEN CAST(CFG_VALUE AS DECIMAL(6,4)) END) / 100.0, 0.03),
        @INS_CEILING       = ISNULL(MAX(CASE WHEN CFG_KEY='INS_CEILING_MONTHLY' THEN CAST(CFG_VALUE AS BIGINT) END), 999999999),
        @TAX_YEAR          = ISNULL(MAX(CASE WHEN CFG_KEY='TAX_YEAR'           THEN CAST(CFG_VALUE AS SMALLINT) END), 1403),
        @TAX_EXEMPT        = ISNULL(MAX(CASE WHEN CFG_KEY='TAX_EXEMPT_MONTHLY' THEN CAST(CFG_VALUE AS BIGINT) END), 0),
        @INS_CEILING_APPLY = ISNULL(CAST(MAX(CASE WHEN CFG_KEY='INS_CEILING_APPLY'  THEN CAST(CFG_VALUE AS INT) END) AS BIT), 1),
        @TAX_DEDUCT_INS    = ISNULL(CAST(MAX(CASE WHEN CFG_KEY='TAX_DEDUCT_INS'     THEN CAST(CFG_VALUE AS INT) END) AS BIT), 1),
        @TAX_DEP_APPLY     = ISNULL(CAST(MAX(CASE WHEN CFG_KEY='TAX_DEPRIVATION_APPLY' THEN CAST(CFG_VALUE AS INT) END) AS BIT), 0),
        @ADV_ENABLED       = ISNULL(CAST(MAX(CASE WHEN CFG_KEY='ADV_ENABLED'        THEN CAST(CFG_VALUE AS INT) END) AS BIT), 0),
        @MONTHLY_PRORATE   = ISNULL(CAST(MAX(CASE WHEN CFG_KEY='MONTHLY_ITEM_PRORATE' THEN CAST(CFG_VALUE AS INT) END) AS BIT), 0)
    FROM PAY2_CONFIG;

    SELECT @PERIOD_DATE = PERIOD_DATE FROM PAY2_PERIOD WHERE PER_ID = @PER_ID;
    IF @PERIOD_DATE IS NULL
    BEGIN
        RAISERROR(N'دوره %d یافت نشد.', 16, 1, @PER_ID);
        RETURN;
    END;

    -- محاسبه طول ماه + تشخیص سال کبیسه شمسی (فقط در حالت MONTH_DAYS_MODE=REAL فعال است)
    SET @PERIOD_MONTH = (@PERIOD_DATE / 100) % 100;
    SET @PERIOD_YEAR  = @PERIOD_DATE / 10000;
    DECLARE @IS_LEAP_YEAR BIT = CASE WHEN ((25 * @PERIOD_YEAR + 11) % 33) < 8 THEN 1 ELSE 0 END; -- چرخه ۳۳ ساله (صحیح برای ۱۳۷۰..۱۴۳۶)

    SET @MONTH_DAYS = CASE
        WHEN @MONTH_DAYS_MODE = '30' THEN 30
        WHEN @PERIOD_MONTH <= 6 THEN 31
        WHEN @PERIOD_MONTH BETWEEN 7 AND 11 THEN 30
        WHEN @PERIOD_MONTH = 12 AND @IS_LEAP_YEAR = 1 THEN 30
        ELSE 29
    END;

    -- بارگذاری شناسه‌های سیستمی خارج از حلقه (رفع N+1)
    DECLARE @INS_DED_ID  INT = (SELECT ITEM_ID FROM PAY2_ITEM_DEF WHERE ITEM_CODE='INS_DED');
    DECLARE @TAX_DED_ID  INT = (SELECT ITEM_ID FROM PAY2_ITEM_DEF WHERE ITEM_CODE='TAX_DED');
    DECLARE @LOAN_DED_ID INT = (SELECT ITEM_ID FROM PAY2_ITEM_DEF WHERE ITEM_CODE='LOAN_DED');
    DECLARE @ADV_DED_ID  INT = (SELECT ITEM_ID FROM PAY2_ITEM_DEF WHERE ITEM_CODE='ADVANCE_DED');

    -- گام ۲ — ایجاد هدر PAY2_RUN
    DECLARE @PREV_RUN_ID INT = NULL;
    DECLARE @PREV_STATUS TINYINT = NULL;
    DECLARE @NEXT_RUN_NO SMALLINT = 1;

    IF @IS_RERUN = 1
    BEGIN
        SELECT TOP 1 @PREV_RUN_ID = RUN_ID, @NEXT_RUN_NO = RUN_NO + 1, @PREV_STATUS = STATUS
        FROM PAY2_RUN WHERE PER_ID = @PER_ID AND IS_LATEST = 1 ORDER BY RUN_NO DESC;

        -- گارد امنیتی: محافظت از اسناد تأیید شده
        IF @PREV_STATUS >= 2
        BEGIN
            RAISERROR(N'اجرای قبلی تأیید نهایی شده است. دیتابیس اجازه بازمحاسبه را نمی‌دهد.', 16, 1);
            RETURN;
        END

        IF @PREV_RUN_ID IS NOT NULL
        BEGIN
            IF EXISTS (SELECT 1 FROM PAY2_RUN WHERE RUN_ID = @PREV_RUN_ID AND STATUS = 1)
               AND EXISTS (SELECT 1 FROM PAY2_RUN_LINE WHERE RUN_ID = @PREV_RUN_ID)
            BEGIN
                EXEC SP_PAY2_REVERT_RUN @RUN_ID = @PREV_RUN_ID, @REVERT_BY = @CALC_BY;
            END
        END

        UPDATE PAY2_RUN SET IS_LATEST = 0 WHERE PER_ID = @PER_ID;
    END;

    INSERT INTO PAY2_RUN (PER_ID, RUN_NO, IS_LATEST, CALC_AT, CALC_BY, STATUS, PREV_RUN_ID)
    VALUES (@PER_ID, @NEXT_RUN_NO, 1, GETDATE(), @CALC_BY, 1, @PREV_RUN_ID);

    SET @NEW_RUN_ID = SCOPE_IDENTITY();

    CREATE TABLE #AdvResult (EMP_ID INT, PCODE NVARCHAR(50), FULL_NAME NVARCHAR(150), RAW_BALANCE BIGINT, MANUAL_EXCL BIGINT, ADVANCE_DEDUCTION BIGINT);
    IF @ADV_ENABLED = 1
    BEGIN
        INSERT INTO #AdvResult (EMP_ID, PCODE, FULL_NAME, RAW_BALANCE, MANUAL_EXCL, ADVANCE_DEDUCTION)
        EXEC SP_PAY2_GET_ADVANCES @PERIOD_DATE = @PERIOD_DATE, @PAYROLL_N_S = @PAYROLL_N_S, @WS_ID = @WS_ID;
    END;

    -- Table Variable برای حفظ پرفورمنس
    DECLARE @ItemCalc TABLE (
        ITEM_ID INT, ITEM_CODE NVARCHAR(30), ITEM_TYPE TINYINT,
        AMOUNT BIGINT, INS_SUBJECT BIT, TAX_SUBJECT BIT
    );

    -- گام ۳ — حلقه روی پرسنل فعال کارگاه
    DECLARE
        @EMP_ID INT, @IS_MANAGER BIT, @INS_TYPE TINYINT,
        @TAX_EXEMPT_FLAG BIT, @REGION_DEP TINYINT, @ACC_T NVARCHAR(50);

    DECLARE @WS_SHIFT_MODE NVARCHAR(10);
    SELECT @WS_SHIFT_MODE = NULLIF(SHIFT_MODE, N'') FROM PAY2_WORKSHOP WHERE WS_ID = @WS_ID;

    DECLARE cur_emp CURSOR LOCAL FAST_FORWARD READ_ONLY FOR
        SELECT E.EMP_ID, E.IS_MANAGER, E.INS_TYPE, E.TAX_EXEMPT, E.REGION_DEPRIVATION, E.ACC_T
        FROM PAY2_EMPLOYEE E
        WHERE E.WS_ID = @WS_ID AND E.IS_ACTIVE = 1
          AND EXISTS (SELECT 1 FROM PAY2_ATTENDANCE A WHERE A.PER_ID = @PER_ID AND A.EMP_ID = E.EMP_ID);

    OPEN cur_emp;
    FETCH NEXT FROM cur_emp INTO @EMP_ID, @IS_MANAGER, @INS_TYPE, @TAX_EXEMPT_FLAG, @REGION_DEP, @ACC_T;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        DELETE FROM @ItemCalc;

        DECLARE
            @WORK_DAYS DECIMAL(5,2)=0, @DAYS DECIMAL(5,2)=0, @DAYSB DECIMAL(5,2)=0,
            @FRID_COUNT TINYINT=0, @TDAYS DECIMAL(5,2)=0, @OT_NORMAL_H DECIMAL(6,2)=0,
            @OT_HOLIDAY_H DECIMAL(6,2)=0, @OT_ADMIN_H DECIMAL(6,2)=0, @LEAVE_DAYS DECIMAL(5,2)=0,
            @PERF_AMOUNT BIGINT=0, @TRANSP_AMOUNT BIGINT=0, @KASR_OTHER BIGINT=0;

        SELECT
            @WORK_DAYS = ISNULL(WORK_DAYS,0), @DAYS = ISNULL(DAYS,0), @DAYSB = ISNULL(DAYSB,0),
            @FRID_COUNT = ISNULL(FRID_COUNT,0), @TDAYS = ISNULL(TDAYS,0), @OT_NORMAL_H = ISNULL(OT_NORMAL_H,0),
            @OT_HOLIDAY_H = ISNULL(OT_HOLIDAY_H,0), @OT_ADMIN_H = ISNULL(OT_ADMIN_H,0), @LEAVE_DAYS = ISNULL(LEAVE_DAYS,0),
            @PERF_AMOUNT = ISNULL(PERF_AMOUNT,0), @TRANSP_AMOUNT = ISNULL(TRANSP_AMOUNT,0), @KASR_OTHER = ISNULL(KASR_OTHER,0)
        FROM PAY2_ATTENDANCE WHERE PER_ID = @PER_ID AND EMP_ID = @EMP_ID;

        DECLARE @DEC_ID INT, @DEC_FROM BIGINT, @DEC_TO BIGINT, @DEC_SHIFT_MODE NVARCHAR(10);
        DECLARE @PER_START BIGINT = @PERIOD_DATE + 1;
        DECLARE @PER_END   BIGINT = @PERIOD_DATE + @MONTH_DAYS;

        DECLARE cur_dec CURSOR LOCAL FAST_FORWARD READ_ONLY FOR
            SELECT DEC_ID, EFF_FROM, ISNULL(EFF_TO, 99991231), NULLIF(SHIFT_MODE, N'')
            FROM PAY2_DECREE
            WHERE EMP_ID = @EMP_ID AND IS_CONFIRMED = 1
              AND EFF_FROM <= @PER_END
              AND (EFF_TO IS NULL OR EFF_TO >= @PER_START)
            ORDER BY EFF_FROM;

        OPEN cur_dec;
        FETCH NEXT FROM cur_dec INTO @DEC_ID, @DEC_FROM, @DEC_TO, @DEC_SHIFT_MODE;

        WHILE @@FETCH_STATUS = 0
        BEGIN
            -- ضریب تناسب برای پوشش ترفیعات وسط ماه
            DECLARE @DEC_ACTUAL_START BIGINT = CASE WHEN @DEC_FROM > @PER_START THEN @DEC_FROM ELSE @PER_START END;
            DECLARE @DEC_ACTUAL_END   BIGINT = CASE WHEN @DEC_TO < @PER_END THEN @DEC_TO ELSE @PER_END END;
            DECLARE @DEC_ACTIVE_DAYS INT = 0;

            IF @DEC_ACTUAL_START <= @DEC_ACTUAL_END
                SET @DEC_ACTIVE_DAYS = (@DEC_ACTUAL_END % 100) - (@DEC_ACTUAL_START % 100) + 1;

            IF @DEC_ACTIVE_DAYS > 0
            BEGIN
                DECLARE @PRORATE_FACTOR DECIMAL(18,6) = CAST(@DEC_ACTIVE_DAYS AS DECIMAL(18,6)) / CAST(@MONTH_DAYS AS DECIMAL(18,6));

                -- مبلغ پایه روزانه خام حکم (برای محاسبه حق شیفت درصدی)
                DECLARE @CURRENT_DEC_DAILY_BASE DECIMAL(18,2) = 0;
                SELECT TOP 1 @CURRENT_DEC_DAILY_BASE = AMOUNT
                FROM PAY2_DECREE_LINE DL INNER JOIN PAY2_ITEM_DEF ID ON DL.ITEM_ID = ID.ITEM_ID
                WHERE DL.DEC_ID = @DEC_ID AND ID.ITEM_CODE IN ('BASE_SAL', 'BASE_SAL_B') ORDER BY DL.AMOUNT DESC;

                DECLARE
                    @ITEM_ID INT, @ITEM_CODE NVARCHAR(30), @ITEM_TYPE TINYINT, @ITEM_AMOUNT DECIMAL(18,2),
                    @ITEM_BASIS TINYINT, @ITEM_INS BIT, @ITEM_TAX BIT, @ITEM_PBD TINYINT, @DL_SHIFT_MODE_OV NVARCHAR(10),
                    @OV_INS BIT, @OV_TAX BIT, @OV_BASIS TINYINT, @CALC_AMOUNT BIGINT = 0;

                DECLARE cur_line CURSOR LOCAL FAST_FORWARD READ_ONLY FOR
                    SELECT DL.ITEM_ID, ID.ITEM_CODE, ID.ITEM_TYPE, ISNULL(DL.AMOUNT, 0),
                        DL.SHIFT_MODE_OV,
                        ISNULL(DL.BASIS_OV, ID.CALC_BASIS), ISNULL(DL.INS_OV, ID.INS_SUBJECT), ISNULL(DL.TAX_OV, ID.TAX_SUBJECT), ID.PAY_BASE_DAYS
                    FROM PAY2_DECREE_LINE DL INNER JOIN PAY2_ITEM_DEF ID ON DL.ITEM_ID = ID.ITEM_ID
                    WHERE DL.DEC_ID = @DEC_ID AND ID.IS_ACTIVE = 1 AND ID.ITEM_CODE NOT IN ('INS_DED','TAX_DED','LOAN_DED','ADVANCE_DED')
                    ORDER BY ID.SORT_ORDER;

                OPEN cur_line;
                FETCH NEXT FROM cur_line INTO @ITEM_ID, @ITEM_CODE, @ITEM_TYPE, @ITEM_AMOUNT, @DL_SHIFT_MODE_OV, @ITEM_BASIS, @ITEM_INS, @ITEM_TAX, @ITEM_PBD;

                WHILE @@FETCH_STATUS = 0
                BEGIN
                    SELECT @OV_INS = NULL, @OV_TAX = NULL, @OV_BASIS = NULL;
                    SELECT TOP 1 @OV_INS = INS_OV, @OV_TAX = TAX_OV, @OV_BASIS = BASIS_OV
                    FROM PAY2_OVERRIDE WHERE EMP_ID = @EMP_ID AND ITEM_ID = @ITEM_ID AND VALID_FROM <= @PERIOD_DATE AND (VALID_TO IS NULL OR VALID_TO >= @PERIOD_DATE) ORDER BY VALID_FROM DESC;

                    IF @OV_INS IS NOT NULL SET @ITEM_INS = @OV_INS;
                    IF @OV_TAX IS NOT NULL SET @ITEM_TAX = @OV_TAX;
                    IF @OV_BASIS IS NOT NULL SET @ITEM_BASIS = @OV_BASIS;

                    DECLARE @PAY_DAYS DECIMAL(18,6) = (CASE @ITEM_PBD WHEN 1 THEN @DAYS ELSE @DAYSB END) * @PRORATE_FACTOR;
                    DECLARE @BASE_DAYS_RAW DECIMAL(5,2) = (CASE @ITEM_PBD WHEN 1 THEN @DAYS ELSE @DAYSB END);

                    -- 🛠 اصلاح باگ ۳۰برابری: مبلغ پایه ماهانه است و باید بر تعداد روز ماه تقسیم شود
                    IF @ITEM_CODE IN ('BASE_SAL', 'BASE_SAL_B')
                        SET @CALC_AMOUNT = CAST(@ITEM_AMOUNT * @PAY_DAYS AS BIGINT);

                    ELSE IF @ITEM_CODE IN ('HOME','CHILDREN','GROCERY')
                    BEGIN
                        DECLARE @FULL_MONTH BIGINT = CASE WHEN @BASE_DAYS_RAW >= 28 THEN CAST(@ITEM_AMOUNT AS BIGINT) ELSE CAST(@ITEM_AMOUNT * (@BASE_DAYS_RAW / 30.0) AS BIGINT) END;
                        SET @CALC_AMOUNT = CAST(@FULL_MONTH * @PRORATE_FACTOR AS BIGINT);
                    END

                    ELSE IF @ITEM_CODE = 'NAHAR'
                    BEGIN
                        DECLARE @NAHAR_DAYS DECIMAL(18,6) = (@DAYSB - @FRID_COUNT - @LEAVE_DAYS + @TDAYS) * @PRORATE_FACTOR;
                        SET @CALC_AMOUNT = CASE WHEN @NAHAR_DAYS > 0 THEN CAST(@ITEM_AMOUNT * @NAHAR_DAYS AS BIGINT) ELSE CAST(@ITEM_AMOUNT * @PAY_DAYS AS BIGINT) END;
                    END

                    ELSE IF @ITEM_CODE = 'SHIFT'
                    BEGIN
                        DECLARE @EFF_SHIFT_MODE NVARCHAR(10) = COALESCE(NULLIF(@DL_SHIFT_MODE_OV, N''), @DEC_SHIFT_MODE, @WS_SHIFT_MODE, @SHIFT_MODE, 'PCT');
                        IF @EFF_SHIFT_MODE = 'FIXED'
                            SET @CALC_AMOUNT = CAST(@ITEM_AMOUNT * (@PAY_DAYS / CAST(@MONTH_DAYS AS DECIMAL(5,2))) AS BIGINT);
                        ELSE
                            -- v6.2 (رفع باگ): @CURRENT_DEC_DAILY_BASE مقدارِ «ماهانه»‌ی پایه است (نه روزانه)؛ ضربِ نادرست در 30 حذف شد تا حق شیفتِ درصدی ۳۰برابر نشود
                            SET @CALC_AMOUNT = CAST(ROUND((@CURRENT_DEC_DAILY_BASE * @PAY_DAYS * @ITEM_AMOUNT / 100.0), 0) AS BIGINT);
                    END

                    -- v6.1 (حفظ‌شده): مبنای ساعتی — آیتم‌های اضافه‌کار از ساعات کارکرد خودشان استفاده می‌کنند
                    ELSE IF @ITEM_BASIS = 3
                        SET @CALC_AMOUNT =
                            CASE @ITEM_CODE
                                WHEN 'OT_NORMAL'  THEN CAST(@ITEM_AMOUNT * @OT_NORMAL_H  AS BIGINT)
                                WHEN 'OT_HOLIDAY' THEN CAST(@ITEM_AMOUNT * @OT_HOLIDAY_H AS BIGINT)
                                WHEN 'OT_ADMIN'   THEN CAST(@ITEM_AMOUNT * @OT_ADMIN_H   AS BIGINT)
                                ELSE CAST(@ITEM_AMOUNT * @PAY_DAYS * @OT_HOUR_BASE AS BIGINT)
                            END;

                    -- آیتم‌های ماهیانه (basis=2): کسر به‌نسبت غیبت اختیاری است (کلید MONTHLY_ITEM_PRORATE)
                    -- PRORATE=1: کاهش با غیبت و تسهیم تغییر حکم وسط ماه | PRORATE=0: فقط تسهیم تغییر حکم، بدون اثر غیبت
                    ELSE IF @ITEM_BASIS = 2
                        SET @CALC_AMOUNT = CASE
                            WHEN @MONTHLY_PRORATE = 1
                                THEN CAST(@ITEM_AMOUNT * (@PAY_DAYS / CAST(@MONTH_DAYS AS DECIMAL(5,2))) AS BIGINT)
                            ELSE CAST(@ITEM_AMOUNT * @PRORATE_FACTOR AS BIGINT)
                        END;

                    -- 🛠 اصلاح باگ ۳۰برابری: آیتم‌های روزانهٔ مبلغ‌ماهانه بر تعداد روز ماه تقسیم می‌شوند
                    ELSE IF @ITEM_BASIS = 1
                        SET @CALC_AMOUNT = CAST(@ITEM_AMOUNT * @PAY_DAYS AS BIGINT);

                    ELSE
                        SET @CALC_AMOUNT = ISNULL(@ITEM_AMOUNT, 0);

                    INSERT INTO @ItemCalc (ITEM_ID, ITEM_CODE, ITEM_TYPE, AMOUNT, INS_SUBJECT, TAX_SUBJECT)
                    VALUES (@ITEM_ID, @ITEM_CODE, @ITEM_TYPE, @CALC_AMOUNT, @ITEM_INS, @ITEM_TAX);

                    FETCH NEXT FROM cur_line INTO @ITEM_ID, @ITEM_CODE, @ITEM_TYPE, @ITEM_AMOUNT, @DL_SHIFT_MODE_OV, @ITEM_BASIS, @ITEM_INS, @ITEM_TAX, @ITEM_PBD;
                END;
                CLOSE cur_line; DEALLOCATE cur_line;
            END;

            FETCH NEXT FROM cur_dec INTO @DEC_ID, @DEC_FROM, @DEC_TO, @DEC_SHIFT_MODE;
        END;
        CLOSE cur_dec; DEALLOCATE cur_dec;

        -- گام ۶ — افزودن آیتم‌های متغیر
        DECLARE @TOTAL_BASE_IN_MONTH BIGINT = ISNULL((SELECT SUM(AMOUNT) FROM @ItemCalc WHERE ITEM_CODE IN ('BASE_SAL', 'BASE_SAL_B')), 0);
        DECLARE @EFFECTIVE_HOURLY DECIMAL(18,2) = 0;

        -- جلوگیری از تقسیم بر صفر + مکانیزم نجات برای پرسنلِ غایب با اضافه‌کار
        IF @DAYSB > 0 AND @OT_HOUR_BASE > 0
        BEGIN
            SET @EFFECTIVE_HOURLY = ISNULL((CAST(@TOTAL_BASE_IN_MONTH AS DECIMAL(18,2)) / @DAYSB) / NULLIF(@OT_HOUR_BASE, 0), 0);
        END
        ELSE IF @OT_HOUR_BASE > 0
        BEGIN
            -- Fallback: مبلغ پایه ماهانه از آخرین حکم؛ تقسیم بر MONTH_DAYS برای رسیدن به نرخ روزانه (اصلاح باگ ۳۰برابری)
            DECLARE @FALLBACK_MONTHLY_BASE BIGINT = 0;
            SELECT TOP 1 @FALLBACK_MONTHLY_BASE = CAST(DL.AMOUNT AS BIGINT)
            FROM PAY2_DECREE D INNER JOIN PAY2_DECREE_LINE DL ON D.DEC_ID = DL.DEC_ID INNER JOIN PAY2_ITEM_DEF ID ON DL.ITEM_ID = ID.ITEM_ID
            WHERE D.EMP_ID = @EMP_ID AND D.IS_CONFIRMED = 1 AND ID.ITEM_CODE IN ('BASE_SAL', 'BASE_SAL_B') ORDER BY D.EFF_FROM DESC;

            SET @EFFECTIVE_HOURLY = ISNULL(CAST(@FALLBACK_MONTHLY_BASE AS DECIMAL(18,2)) / NULLIF(@OT_HOUR_BASE, 0), 0);
        END

        IF @OT_NORMAL_H > 0 AND NOT EXISTS (SELECT 1 FROM @ItemCalc WHERE ITEM_CODE = 'OT_NORMAL')
            INSERT INTO @ItemCalc (ITEM_ID, ITEM_CODE, ITEM_TYPE, AMOUNT, INS_SUBJECT, TAX_SUBJECT)
            SELECT ITEM_ID, 'OT_NORMAL', 2, CAST(@EFFECTIVE_HOURLY * @OT_NORMAL_H * @OT_NORMAL_MULT AS BIGINT), INS_SUBJECT, TAX_SUBJECT FROM PAY2_ITEM_DEF WHERE ITEM_CODE = 'OT_NORMAL';

        IF @OT_HOLIDAY_H > 0 AND NOT EXISTS (SELECT 1 FROM @ItemCalc WHERE ITEM_CODE = 'OT_HOLIDAY')
            INSERT INTO @ItemCalc (ITEM_ID, ITEM_CODE, ITEM_TYPE, AMOUNT, INS_SUBJECT, TAX_SUBJECT)
            SELECT ITEM_ID, 'OT_HOLIDAY', 2, CAST(@EFFECTIVE_HOURLY * @OT_HOLIDAY_H * @OT_HOLIDAY_MULT AS BIGINT), INS_SUBJECT, TAX_SUBJECT FROM PAY2_ITEM_DEF WHERE ITEM_CODE = 'OT_HOLIDAY';

        IF @OT_ADMIN_H > 0 AND NOT EXISTS (SELECT 1 FROM @ItemCalc WHERE ITEM_CODE = 'OT_ADMIN')
            INSERT INTO @ItemCalc (ITEM_ID, ITEM_CODE, ITEM_TYPE, AMOUNT, INS_SUBJECT, TAX_SUBJECT)
            SELECT ITEM_ID, 'OT_ADMIN', 2, CAST(@EFFECTIVE_HOURLY * @OT_ADMIN_H * @OT_NORMAL_MULT AS BIGINT), INS_SUBJECT, TAX_SUBJECT FROM PAY2_ITEM_DEF WHERE ITEM_CODE = 'OT_ADMIN';

        IF @PERF_AMOUNT > 0
            INSERT INTO @ItemCalc (ITEM_ID, ITEM_CODE, ITEM_TYPE, AMOUNT, INS_SUBJECT, TAX_SUBJECT)
            SELECT ITEM_ID, 'PERF_BONUS', 2, @PERF_AMOUNT, INS_SUBJECT, TAX_SUBJECT FROM PAY2_ITEM_DEF WHERE ITEM_CODE = 'PERF_BONUS';

        IF @TRANSP_AMOUNT > 0
            INSERT INTO @ItemCalc (ITEM_ID, ITEM_CODE, ITEM_TYPE, AMOUNT, INS_SUBJECT, TAX_SUBJECT)
            SELECT ITEM_ID, 'TRANSP', 2, @TRANSP_AMOUNT, INS_SUBJECT, TAX_SUBJECT FROM PAY2_ITEM_DEF WHERE ITEM_CODE = 'TRANSP';

        -- v6.1 (حفظ‌شده): گارد ضدِ دوبار‌شماری آیتم‌هایی که هم در حکم و هم در PAY2_ATT_VALUE هستند
        INSERT INTO @ItemCalc (ITEM_ID, ITEM_CODE, ITEM_TYPE, AMOUNT, INS_SUBJECT, TAX_SUBJECT)
        SELECT AV.ITEM_ID, ID.ITEM_CODE, ID.ITEM_TYPE, AV.VALUE, ID.INS_SUBJECT, ID.TAX_SUBJECT
        FROM PAY2_ATT_VALUE AV INNER JOIN PAY2_ITEM_DEF ID ON AV.ITEM_ID = ID.ITEM_ID
        WHERE AV.PER_ID = @PER_ID AND AV.EMP_ID = @EMP_ID AND AV.VALUE <> 0
          AND NOT EXISTS (SELECT 1 FROM @ItemCalc X WHERE X.ITEM_ID = AV.ITEM_ID);

        -- گام ۷ — محاسبه بیمه
        DECLARE @GROSS_PAY BIGINT=0, @INS_BASE BIGINT=0, @INS_WORKER BIGINT=0, @INS_EMPLOYER BIGINT=0;

        SELECT @GROSS_PAY = ISNULL(SUM(AMOUNT), 0) FROM @ItemCalc WHERE ITEM_TYPE IN (1, 2);
        SELECT @INS_BASE = ISNULL(SUM(AMOUNT), 0) FROM @ItemCalc WHERE INS_SUBJECT = 1 AND ITEM_TYPE IN (1, 2);

        DECLARE @EFFECTIVE_INS_CEILING BIGINT = CAST((@INS_CEILING / 30.0) * @DAYSB AS BIGINT);
        IF @INS_CEILING_APPLY = 1 AND @INS_TYPE <> 3
            SET @INS_BASE = CASE WHEN @INS_BASE > @EFFECTIVE_INS_CEILING THEN @EFFECTIVE_INS_CEILING ELSE @INS_BASE END;

        IF @INS_TYPE = 3
        BEGIN
            SET @INS_BASE = 0; SET @INS_WORKER = 0; SET @INS_EMPLOYER = 0;
        END;
        ELSE
        BEGIN
            SET @INS_WORKER = ISNULL(CAST(@INS_BASE * @INS_WORKER_RATE AS BIGINT), 0);
            DECLARE @EMP_IS_JANBAZ BIT = ISNULL((SELECT IS_JANBAZ FROM PAY2_EMPLOYEE WHERE EMP_ID = @EMP_ID), 0);
            DECLARE @JANBAZ_RATE DECIMAL(6,4) = ISNULL(CAST((SELECT CFG_VALUE FROM PAY2_CONFIG WHERE CFG_KEY='INS_JANBAZ_RATE') AS DECIMAL(6,4)), 0.18);

            IF @EMP_IS_JANBAZ = 1
                SET @INS_EMPLOYER = ISNULL(CAST(@INS_BASE * @JANBAZ_RATE AS BIGINT), 0);
            ELSE
                SET @INS_EMPLOYER = ISNULL(CAST(@INS_BASE * (@INS_EMPLOYER_RATE + CASE WHEN ISNULL(@IS_MANAGER,0)=0 THEN @INS_UNEMP_RATE ELSE 0 END) AS BIGINT), 0);
        END;

        -- گام ۸ — محاسبه مالیات
        DECLARE @TAX_BASE BIGINT=0, @TAX_AMOUNT BIGINT=0;
        IF @TAX_EXEMPT_FLAG = 1
        BEGIN
            SET @TAX_BASE = 0; SET @TAX_AMOUNT = 0;
        END;
        ELSE
        BEGIN
            SELECT @TAX_BASE = ISNULL(SUM(AMOUNT), 0) FROM @ItemCalc WHERE TAX_SUBJECT = 1 AND ITEM_TYPE IN (1, 2);
            IF @TAX_DEDUCT_INS = 1 SET @TAX_BASE = @TAX_BASE - @INS_WORKER;
            SET @TAX_BASE = CASE WHEN @TAX_BASE > @TAX_EXEMPT THEN @TAX_BASE - @TAX_EXEMPT ELSE 0 END;
            IF @TAX_DEP_APPLY = 1 AND @REGION_DEP > 0 SET @TAX_BASE = CAST(@TAX_BASE * (1.0 - @REGION_DEP / 100.0) AS BIGINT);
            SET @TAX_AMOUNT = ISNULL([dbo].[FN_PAY2_CALC_TAX](@TAX_BASE * 12, @TAX_YEAR) / 12, 0);
            IF @TAX_AMOUNT < 0 SET @TAX_AMOUNT = 0;
        END;

        DECLARE @ADVANCE_DED BIGINT = 0;
        IF @ADV_ENABLED = 1 SELECT @ADVANCE_DED = ISNULL(ADVANCE_DEDUCTION, 0) FROM #AdvResult WHERE EMP_ID = @EMP_ID;

        DECLARE @LOAN_DED BIGINT = 0;
        SELECT @LOAN_DED = ISNULL(SUM(LS.AMOUNT), 0) FROM PAY2_LOAN_SCHED LS INNER JOIN PAY2_LOAN L ON LS.LOAN_ID = L.LOAN_ID
        WHERE L.EMP_ID = @EMP_ID AND L.IS_ACTIVE = 1 AND LS.DUE_PERIOD = @PERIOD_DATE AND LS.RUN_ID IS NULL;

        DECLARE @OTHER_DED BIGINT = ISNULL(@KASR_OTHER, 0);
        DECLARE @TOTAL_DED BIGINT = @INS_WORKER + @TAX_AMOUNT + @LOAN_DED + @ADVANCE_DED + @OTHER_DED;
        DECLARE @NET_PAY BIGINT = @GROSS_PAY - @TOTAL_DED;

        IF @ROUND_MODE > 1 SET @NET_PAY = ISNULL(ROUND(@NET_PAY / CAST(@ROUND_MODE AS FLOAT), 0) * @ROUND_MODE, 0);

        DECLARE @LEAVE_BAL_DAYS DECIMAL(5,2) = NULL;
        SELECT @LEAVE_BAL_DAYS = CAST(BALANCE_MIN AS DECIMAL(10,2)) / 440.0 FROM PAY2_LEAVE_BAL WHERE EMP_ID = @EMP_ID AND YEAR = @PERIOD_DATE / 10000;
        DECLARE @LOAN_BAL BIGINT = NULL;
        SELECT @LOAN_BAL = ISNULL(SUM(BALANCE), 0) FROM V_PAY2_LOAN_BALANCE WHERE EMP_ID = @EMP_ID;

        INSERT INTO PAY2_RUN_LINE (
            RUN_ID, EMP_ID, WORK_DAYS, GROSS_PAY, INS_BASE, INS_WORKER, INS_EMPLOYER, TAX_BASE, TAX_AMOUNT,
            LOAN_DED, ADVANCE_DED, OTHER_DED, TOTAL_DED, NET_PAY, LEAVE_BAL_DAYS, LOAN_BALANCE, ADVANCE_BALANCE_SNAP
        ) VALUES (
            @NEW_RUN_ID, @EMP_ID, @DAYSB, @GROSS_PAY, @INS_BASE, @INS_WORKER, @INS_EMPLOYER, @TAX_BASE, @TAX_AMOUNT,
            @LOAN_DED, @ADVANCE_DED, @OTHER_DED, @TOTAL_DED, @NET_PAY, @LEAVE_BAL_DAYS, @LOAN_BAL, @ADVANCE_DED
        );

        -- پیشگیری از PK Violation + فیلتر مبالغ صفر برای تمیزی فیش
        INSERT INTO PAY2_RUN_DETAIL (RUN_ID, EMP_ID, ITEM_ID, AMOUNT, INS_SUBJECT, TAX_SUBJECT)
        SELECT @NEW_RUN_ID, @EMP_ID, ITEM_ID, SUM(AMOUNT), MAX(CAST(INS_SUBJECT AS INT)), MAX(CAST(TAX_SUBJECT AS INT))
        FROM @ItemCalc GROUP BY ITEM_ID HAVING SUM(AMOUNT) <> 0;

        IF @INS_WORKER  > 0 AND @INS_DED_ID IS NOT NULL INSERT INTO PAY2_RUN_DETAIL (RUN_ID, EMP_ID, ITEM_ID, AMOUNT, INS_SUBJECT, TAX_SUBJECT) VALUES (@NEW_RUN_ID,@EMP_ID,@INS_DED_ID, @INS_WORKER, 0,0);
        IF @TAX_AMOUNT  > 0 AND @TAX_DED_ID IS NOT NULL INSERT INTO PAY2_RUN_DETAIL (RUN_ID, EMP_ID, ITEM_ID, AMOUNT, INS_SUBJECT, TAX_SUBJECT) VALUES (@NEW_RUN_ID,@EMP_ID,@TAX_DED_ID, @TAX_AMOUNT, 0,0);
        IF @LOAN_DED    > 0 AND @LOAN_DED_ID IS NOT NULL INSERT INTO PAY2_RUN_DETAIL (RUN_ID, EMP_ID, ITEM_ID, AMOUNT, INS_SUBJECT, TAX_SUBJECT) VALUES (@NEW_RUN_ID,@EMP_ID,@LOAN_DED_ID,@LOAN_DED,   0,0);
        IF @ADVANCE_DED > 0 AND @ADV_DED_ID IS NOT NULL INSERT INTO PAY2_RUN_DETAIL (RUN_ID, EMP_ID, ITEM_ID, AMOUNT, INS_SUBJECT, TAX_SUBJECT) VALUES (@NEW_RUN_ID,@EMP_ID,@ADV_DED_ID, @ADVANCE_DED,0,0);

        UPDATE PAY2_LOAN_SCHED SET RUN_ID = @NEW_RUN_ID, PAID_AT = GETDATE()
        WHERE DUE_PERIOD = @PERIOD_DATE AND RUN_ID IS NULL AND LOAN_ID IN (SELECT LOAN_ID FROM PAY2_LOAN WHERE EMP_ID=@EMP_ID AND IS_ACTIVE=1);

        UPDATE L
        SET L.PAID_INST = L.PAID_INST + (
            SELECT COUNT(1) FROM PAY2_LOAN_SCHED LS WHERE LS.LOAN_ID = L.LOAN_ID AND LS.RUN_ID = @NEW_RUN_ID
        )
        FROM PAY2_LOAN L
        WHERE L.EMP_ID = @EMP_ID AND L.IS_ACTIVE = 1
          AND EXISTS (SELECT 1 FROM PAY2_LOAN_SCHED LS WHERE LS.LOAN_ID = L.LOAN_ID AND LS.RUN_ID = @NEW_RUN_ID);

        DECLARE @LEAVE_MIN_USED INT = CAST(@LEAVE_DAYS * 440 AS INT);
        IF @LEAVE_MIN_USED > 0
        BEGIN
            IF EXISTS (SELECT 1 FROM PAY2_LEAVE_BAL WHERE EMP_ID = @EMP_ID AND YEAR = @PERIOD_DATE / 10000)
            BEGIN
                UPDATE PAY2_LEAVE_BAL SET USED_MIN = USED_MIN + @LEAVE_MIN_USED, UPDATED_AT = GETDATE()
                WHERE EMP_ID = @EMP_ID AND YEAR = @PERIOD_DATE / 10000;
            END
            ELSE
            BEGIN
                INSERT INTO PAY2_LEAVE_BAL (EMP_ID, YEAR, ENTITLEMENT_MIN, USED_MIN, CARRIED_IN_MIN, CARRIED_OUT_MIN, UPDATED_AT)
                VALUES (@EMP_ID, @PERIOD_DATE / 10000, 11440, @LEAVE_MIN_USED, 0, 0, GETDATE());
            END
        END;

        FETCH NEXT FROM cur_emp INTO @EMP_ID, @IS_MANAGER, @INS_TYPE, @TAX_EXEMPT_FLAG, @REGION_DEP, @ACC_T;
    END;

    CLOSE cur_emp; DEALLOCATE cur_emp;
    DROP TABLE #AdvResult;

    UPDATE PAY2_PERIOD SET STATUS = 3 WHERE PER_ID = @PER_ID;

END;
GO
