SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF COL_LENGTH('dbo.PAY2_RUN_DETAIL','NOMINAL_AMOUNT') IS NULL ALTER TABLE dbo.PAY2_RUN_DETAIL ADD NOMINAL_AMOUNT BIGINT NULL;
IF COL_LENGTH('dbo.PAY2_RUN_DETAIL','ITEM_CODE_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_DETAIL ADD ITEM_CODE_SNAP NVARCHAR(30) NULL;
IF COL_LENGTH('dbo.PAY2_RUN_DETAIL','CALC_BASIS_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_DETAIL ADD CALC_BASIS_SNAP TINYINT NULL;
IF COL_LENGTH('dbo.PAY2_RUN_DETAIL','ITEM_TYPE_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_DETAIL ADD ITEM_TYPE_SNAP TINYINT NULL;
IF COL_LENGTH('dbo.PAY2_RUN_LINE','NOMINAL_GROSS') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD NOMINAL_GROSS BIGINT NULL;
IF COL_LENGTH('dbo.PAY2_RUN_LINE','NOMINAL_DAYS') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD NOMINAL_DAYS DECIMAL(5,2) NULL;
IF COL_LENGTH('dbo.PAY2_RUN_LINE','ROUNDING_ADJ') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD ROUNDING_ADJ BIGINT NULL;
IF COL_LENGTH('dbo.PAY2_RUN_LINE','HIRE_DATE_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD HIRE_DATE_SNAP BIGINT NULL;
IF COL_LENGTH('dbo.PAY2_RUN_LINE','FIRE_DATE_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD FIRE_DATE_SNAP BIGINT NULL;
IF NOT EXISTS(SELECT 1 FROM dbo.PAY2_ITEM_DEF WHERE ITEM_CODE='SANOVAT_PAYE')
 INSERT dbo.PAY2_ITEM_DEF(ITEM_CODE,ITEM_NAME,ITEM_TYPE,CALC_BASIS,INS_SUBJECT,TAX_SUBJECT,INS_BASE_DAYS,PAY_BASE_DAYS,IS_SYSTEM,SHOW_IN_SLIP,SORT_ORDER,IS_ACTIVE,NOTES)
 VALUES('SANOVAT_PAYE',N'پایه سنوات روزانه',1,1,1,1,1,2,1,1,3,1,N'مشمولیت قابل تنظیم در آیتم، حکم یا Override');

IF OBJECT_ID(N'dbo.PAY2_SANOVAT_MIGRATION_INPUT', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.PAY2_SANOVAT_MIGRATION_INPUT
    (
        DEC_ID INT NOT NULL CONSTRAINT PK_PAY2_SANOVAT_MIGRATION_INPUT PRIMARY KEY,
        SENIORITY_DAILY_AMOUNT DECIMAL(18,2) NOT NULL,
        IS_APPROVED BIT NOT NULL CONSTRAINT DF_PAY2_SMI_APPROVED DEFAULT(0),
        SOURCE_NOTE NVARCHAR(300) NOT NULL,
        ENTERED_BY INT NULL,
        ENTERED_AT DATETIME2 NOT NULL CONSTRAINT DF_PAY2_SMI_AT DEFAULT(SYSDATETIME()),
        CONSTRAINT CK_PAY2_SMI_AMOUNT CHECK (SENIORITY_DAILY_AMOUNT >= 0),
        CONSTRAINT FK_PAY2_SMI_DEC FOREIGN KEY (DEC_ID) REFERENCES dbo.PAY2_DECREE(DEC_ID)
    );
END;

IF OBJECT_ID(N'dbo.PAY2_SANOVAT_MIGRATION_LOG', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.PAY2_SANOVAT_MIGRATION_LOG
    (
        DEC_ID INT NOT NULL CONSTRAINT PK_PAY2_SANOVAT_MIGRATION_LOG PRIMARY KEY,
        BASE_BEFORE DECIMAL(18,2) NOT NULL,
        SENIORITY_AMOUNT DECIMAL(18,2) NOT NULL,
        BASE_AFTER DECIMAL(18,2) NOT NULL,
        APPLIED_BY INT NULL,
        APPLIED_AT DATETIME2 NOT NULL CONSTRAINT DF_PAY2_SML_AT DEFAULT(SYSDATETIME()),
        CONSTRAINT FK_PAY2_SML_DEC FOREIGN KEY (DEC_ID) REFERENCES dbo.PAY2_DECREE(DEC_ID)
    );
END;
COMMIT;
GO

CREATE OR ALTER PROCEDURE dbo.SP_PAY2_PREVIEW_SANOVAT_MIGRATION
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @SeniorityItemId INT=(SELECT ITEM_ID FROM dbo.PAY2_ITEM_DEF WHERE ITEM_CODE='SANOVAT_PAYE');
    SELECT D.DEC_ID, D.EMP_ID, E.EMP_CODE, E.LAST_NAME + N' ' + E.FIRST_NAME FULL_NAME,
           D.EFF_FROM, D.EFF_TO, B.AMOUNT BASE_BEFORE,
           I.SENIORITY_DAILY_AMOUNT,
           B.AMOUNT-I.SENIORITY_DAILY_AMOUNT BASE_AFTER,
           (B.AMOUNT-I.SENIORITY_DAILY_AMOUNT)+I.SENIORITY_DAILY_AMOUNT TOTAL_AFTER,
           B.AMOUNT TOTAL_BEFORE,
           I.IS_APPROVED, I.SOURCE_NOTE,
           CASE WHEN I.DEC_ID IS NULL THEN N'مبلغ واقعی سنوات ثبت نشده؛ اعمال ممنوع'
                WHEN I.IS_APPROVED=0 THEN N'در انتظار تأیید'
                WHEN I.SENIORITY_DAILY_AMOUNT>B.AMOUNT THEN N'خطا: سنوات بیشتر از پایه مزد'
                WHEN L.DEC_ID IS NOT NULL THEN N'قبلاً اعمال شده'
                WHEN S.ITEM_ID IS NOT NULL THEN N'پایه سنوات از قبل در حکم وجود دارد'
                ELSE N'آماده اعمال' END MIGRATION_STATUS
    FROM dbo.PAY2_DECREE D
    INNER JOIN dbo.PAY2_EMPLOYEE E ON E.EMP_ID=D.EMP_ID
    INNER JOIN dbo.PAY2_DECREE_LINE B ON B.DEC_ID=D.DEC_ID
    INNER JOIN dbo.PAY2_ITEM_DEF BI ON BI.ITEM_ID=B.ITEM_ID AND BI.ITEM_CODE='BASE_SAL'
    LEFT JOIN dbo.PAY2_SANOVAT_MIGRATION_INPUT I ON I.DEC_ID=D.DEC_ID
    LEFT JOIN dbo.PAY2_SANOVAT_MIGRATION_LOG L ON L.DEC_ID=D.DEC_ID
    LEFT JOIN dbo.PAY2_DECREE_LINE S ON S.DEC_ID=D.DEC_ID AND S.ITEM_ID=@SeniorityItemId
    WHERE D.IS_CONFIRMED=1
    ORDER BY E.LAST_NAME,E.FIRST_NAME,D.EFF_FROM;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_PAY2_APPLY_SANOVAT_MIGRATION @APPLIED_BY INT=NULL
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        DECLARE @ItemId INT=(SELECT ITEM_ID FROM dbo.PAY2_ITEM_DEF WITH (UPDLOCK,HOLDLOCK) WHERE ITEM_CODE='SANOVAT_PAYE');
        IF @ItemId IS NULL THROW 51000, N'آیتم SANOVAT_PAYE نصب نشده است.', 1;
        IF EXISTS (SELECT 1 FROM dbo.PAY2_SANOVAT_MIGRATION_INPUT I JOIN dbo.PAY2_DECREE_LINE B ON B.DEC_ID=I.DEC_ID JOIN dbo.PAY2_ITEM_DEF BI ON BI.ITEM_ID=B.ITEM_ID AND BI.ITEM_CODE='BASE_SAL' WHERE I.IS_APPROVED=1 AND I.SENIORITY_DAILY_AMOUNT>B.AMOUNT)
            THROW 51001, N'حداقل یک مبلغ سنوات از پایه مزد بیشتر است.', 1;

        DECLARE @Work TABLE(DEC_ID INT PRIMARY KEY, BASE_BEFORE DECIMAL(18,2), SENIORITY DECIMAL(18,2), BASE_AFTER DECIMAL(18,2));
        INSERT @Work
        SELECT I.DEC_ID,B.AMOUNT,I.SENIORITY_DAILY_AMOUNT,B.AMOUNT-I.SENIORITY_DAILY_AMOUNT
        FROM dbo.PAY2_SANOVAT_MIGRATION_INPUT I
        JOIN dbo.PAY2_DECREE D ON D.DEC_ID=I.DEC_ID AND D.IS_CONFIRMED=1
        JOIN dbo.PAY2_DECREE_LINE B ON B.DEC_ID=D.DEC_ID
        JOIN dbo.PAY2_ITEM_DEF BI ON BI.ITEM_ID=B.ITEM_ID AND BI.ITEM_CODE='BASE_SAL'
        LEFT JOIN dbo.PAY2_SANOVAT_MIGRATION_LOG L ON L.DEC_ID=D.DEC_ID
        LEFT JOIN dbo.PAY2_DECREE_LINE S ON S.DEC_ID=D.DEC_ID AND S.ITEM_ID=@ItemId
        WHERE I.IS_APPROVED=1 AND L.DEC_ID IS NULL AND S.ITEM_ID IS NULL;

        UPDATE B SET AMOUNT=W.BASE_AFTER FROM dbo.PAY2_DECREE_LINE B JOIN @Work W ON W.DEC_ID=B.DEC_ID JOIN dbo.PAY2_ITEM_DEF I ON I.ITEM_ID=B.ITEM_ID AND I.ITEM_CODE='BASE_SAL';
        INSERT dbo.PAY2_DECREE_LINE(DEC_ID,ITEM_ID,AMOUNT) SELECT DEC_ID,@ItemId,SENIORITY FROM @Work;
        INSERT dbo.PAY2_SANOVAT_MIGRATION_LOG(DEC_ID,BASE_BEFORE,SENIORITY_AMOUNT,BASE_AFTER,APPLIED_BY)
        SELECT DEC_ID,BASE_BEFORE,SENIORITY,BASE_AFTER,@APPLIED_BY FROM @Work;
        IF EXISTS (SELECT 1 FROM @Work WHERE BASE_BEFORE<>BASE_AFTER+SENIORITY) THROW 51002,N'کنترل تساوی قبل و بعد ناموفق بود.',1;
        COMMIT;
        SELECT COUNT(*) APPLIED_COUNT FROM @Work;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT>0 ROLLBACK;
        THROW;
    END CATCH
END;
GO
