SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF COL_LENGTH('dbo.PAY2_DECREE_LINE','NOMINAL_AMOUNT_OV') IS NULL ALTER TABLE dbo.PAY2_DECREE_LINE ADD NOMINAL_AMOUNT_OV DECIMAL(18,2) NULL;
IF COL_LENGTH('dbo.PAY2_DECREE_LINE','OFFICIAL_AMOUNT_OV') IS NULL ALTER TABLE dbo.PAY2_DECREE_LINE ADD OFFICIAL_AMOUNT_OV DECIMAL(18,2) NULL;
IF COL_LENGTH('dbo.PAY2_RUN_DETAIL','NOMINAL_AMOUNT') IS NULL ALTER TABLE dbo.PAY2_RUN_DETAIL ADD NOMINAL_AMOUNT BIGINT NULL;
IF COL_LENGTH('dbo.PAY2_RUN_DETAIL','ITEM_CODE_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_DETAIL ADD ITEM_CODE_SNAP NVARCHAR(30) NULL;
IF COL_LENGTH('dbo.PAY2_RUN_DETAIL','CALC_BASIS_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_DETAIL ADD CALC_BASIS_SNAP TINYINT NULL;
IF COL_LENGTH('dbo.PAY2_RUN_DETAIL','ITEM_TYPE_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_DETAIL ADD ITEM_TYPE_SNAP TINYINT NULL;
IF COL_LENGTH('dbo.PAY2_RUN_LINE','NOMINAL_GROSS') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD NOMINAL_GROSS BIGINT NULL;
IF COL_LENGTH('dbo.PAY2_RUN_LINE','NOMINAL_DAYS') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD NOMINAL_DAYS DECIMAL(5,2) NULL;
IF COL_LENGTH('dbo.PAY2_RUN_LINE','INS_EMPLOYER_BASE') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD INS_EMPLOYER_BASE BIGINT NULL;
IF COL_LENGTH('dbo.PAY2_RUN_LINE','INS_UNEMPLOYMENT') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD INS_UNEMPLOYMENT BIGINT NULL;
IF COL_LENGTH('dbo.PAY2_RUN_LINE','ROUNDING_ADJ') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD ROUNDING_ADJ BIGINT NULL;
IF COL_LENGTH('dbo.PAY2_RUN_LINE','HIRE_DATE_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD HIRE_DATE_SNAP BIGINT NULL;
IF COL_LENGTH('dbo.PAY2_RUN_LINE','FIRE_DATE_SNAP') IS NULL ALTER TABLE dbo.PAY2_RUN_LINE ADD FIRE_DATE_SNAP BIGINT NULL;
IF NOT EXISTS(SELECT 1 FROM dbo.PAY2_ITEM_DEF WHERE ITEM_CODE='SANOVAT_PAYE')
 INSERT dbo.PAY2_ITEM_DEF(ITEM_CODE,ITEM_NAME,ITEM_TYPE,CALC_BASIS,INS_SUBJECT,TAX_SUBJECT,INS_BASE_DAYS,PAY_BASE_DAYS,IS_SYSTEM,SHOW_IN_SLIP,SORT_ORDER,IS_ACTIVE,NOTES)
 VALUES('SANOVAT_PAYE',N'پایه سنوات روزانه',1,1,1,1,1,2,1,1,3,1,N'مبلغ روزانه دو ریلی؛ مشمولیت از Snapshot مؤثر Run خوانده می‌شود');

IF OBJECT_ID(N'dbo.PAY2_SANOVAT_MIGRATION_INPUT',N'U') IS NULL
 CREATE TABLE dbo.PAY2_SANOVAT_MIGRATION_INPUT
 (
   DEC_ID INT NOT NULL CONSTRAINT PK_PAY2_SANOVAT_MIGRATION_INPUT PRIMARY KEY,
   SOURCE_RAIL NVARCHAR(10) NULL,
   NOMINAL_SENIORITY_DAILY DECIMAL(18,2) NULL,
   OFFICIAL_SENIORITY_DAILY DECIMAL(18,2) NULL,
   IS_APPROVED BIT NOT NULL CONSTRAINT DF_PAY2_SMI_APPROVED DEFAULT(0),
   SOURCE_NOTE NVARCHAR(300) NOT NULL,
   ENTERED_BY INT NULL,
   ENTERED_AT DATETIME2 NOT NULL CONSTRAINT DF_PAY2_SMI_AT DEFAULT(SYSDATETIME()),
   CONSTRAINT FK_PAY2_SMI_DEC FOREIGN KEY(DEC_ID) REFERENCES dbo.PAY2_DECREE(DEC_ID)
 );
ELSE
BEGIN
 IF COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_INPUT','SENIORITY_DAILY_AMOUNT') IS NOT NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_INPUT ALTER COLUMN SENIORITY_DAILY_AMOUNT DECIMAL(18,2) NULL;
 IF COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_INPUT','SOURCE_RAIL') IS NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_INPUT ADD SOURCE_RAIL NVARCHAR(10) NULL;
 IF COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_INPUT','NOMINAL_SENIORITY_DAILY') IS NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_INPUT ADD NOMINAL_SENIORITY_DAILY DECIMAL(18,2) NULL;
 IF COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_INPUT','OFFICIAL_SENIORITY_DAILY') IS NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_INPUT ADD OFFICIAL_SENIORITY_DAILY DECIMAL(18,2) NULL;
END;

IF OBJECT_ID(N'dbo.PAY2_SANOVAT_MIGRATION_LOG',N'U') IS NULL
 CREATE TABLE dbo.PAY2_SANOVAT_MIGRATION_LOG
 (
   DEC_ID INT NOT NULL CONSTRAINT PK_PAY2_SANOVAT_MIGRATION_LOG PRIMARY KEY,
   SOURCE_RAIL NVARCHAR(10) NOT NULL,
   NOMINAL_BASE_BEFORE DECIMAL(18,2) NULL, NOMINAL_SENIORITY DECIMAL(18,2) NOT NULL, NOMINAL_BASE_AFTER DECIMAL(18,2) NULL,
   OFFICIAL_BASE_BEFORE DECIMAL(18,2) NULL, OFFICIAL_SENIORITY DECIMAL(18,2) NOT NULL, OFFICIAL_BASE_AFTER DECIMAL(18,2) NULL,
   APPLIED_BY INT NULL, APPLIED_AT DATETIME2 NOT NULL CONSTRAINT DF_PAY2_SML_AT DEFAULT(SYSDATETIME()),
   CONSTRAINT FK_PAY2_SML_DEC FOREIGN KEY(DEC_ID) REFERENCES dbo.PAY2_DECREE(DEC_ID)
 );
ELSE
BEGIN
 IF COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_LOG','BASE_BEFORE') IS NOT NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_LOG ALTER COLUMN BASE_BEFORE DECIMAL(18,2) NULL;
 IF COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_LOG','SENIORITY_AMOUNT') IS NOT NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_LOG ALTER COLUMN SENIORITY_AMOUNT DECIMAL(18,2) NULL;
 IF COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_LOG','BASE_AFTER') IS NOT NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_LOG ALTER COLUMN BASE_AFTER DECIMAL(18,2) NULL;
 IF COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_LOG','SOURCE_RAIL') IS NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_LOG ADD SOURCE_RAIL NVARCHAR(10) NULL;
 IF COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_LOG','NOMINAL_BASE_BEFORE') IS NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_LOG ADD NOMINAL_BASE_BEFORE DECIMAL(18,2) NULL, NOMINAL_SENIORITY DECIMAL(18,2) NULL, NOMINAL_BASE_AFTER DECIMAL(18,2) NULL;
 IF COL_LENGTH('dbo.PAY2_SANOVAT_MIGRATION_LOG','OFFICIAL_BASE_BEFORE') IS NULL ALTER TABLE dbo.PAY2_SANOVAT_MIGRATION_LOG ADD OFFICIAL_BASE_BEFORE DECIMAL(18,2) NULL, OFFICIAL_SENIORITY DECIMAL(18,2) NULL, OFFICIAL_BASE_AFTER DECIMAL(18,2) NULL;
END;
COMMIT;
GO

CREATE OR ALTER PROCEDURE dbo.SP_PAY2_PREVIEW_SANOVAT_MIGRATION
AS
BEGIN
 SET NOCOUNT ON;
 DECLARE @ItemId INT=(SELECT ITEM_ID FROM dbo.PAY2_ITEM_DEF WHERE ITEM_CODE='SANOVAT_PAYE');
 DECLARE @AsOf BIGINT=ISNULL((SELECT MAX(PERIOD_DATE)+31 FROM dbo.PAY2_PERIOD),99991231);
 SELECT D.DEC_ID,D.EMP_ID,E.EMP_CODE,E.LAST_NAME+N' '+E.FIRST_NAME FULL_NAME,D.EFF_FROM,D.EFF_TO,
   I.SOURCE_RAIL,I.NOMINAL_SENIORITY_DAILY,I.OFFICIAL_SENIORITY_DAILY,I.IS_APPROVED,I.SOURCE_NOTE,
   BN.AMOUNT NOMINAL_BASE_BEFORE,
   CASE WHEN I.SOURCE_RAIL IN('NOMINAL','BOTH') THEN BN.AMOUNT-I.NOMINAL_SENIORITY_DAILY ELSE BN.AMOUNT END NOMINAL_BASE_AFTER,
   CASE WHEN I.SOURCE_RAIL IN('NOMINAL','BOTH') THEN BN.AMOUNT-I.NOMINAL_SENIORITY_DAILY+I.NOMINAL_SENIORITY_DAILY ELSE BN.AMOUNT END NOMINAL_TOTAL_AFTER,
   BO.AMOUNT OFFICIAL_BASE_BEFORE,
   CASE WHEN I.SOURCE_RAIL IN('OFFICIAL','BOTH') THEN BO.AMOUNT-I.OFFICIAL_SENIORITY_DAILY ELSE BO.AMOUNT END OFFICIAL_BASE_AFTER,
   CASE WHEN I.SOURCE_RAIL IN('OFFICIAL','BOTH') THEN BO.AMOUNT-I.OFFICIAL_SENIORITY_DAILY+I.OFFICIAL_SENIORITY_DAILY ELSE BO.AMOUNT END OFFICIAL_TOTAL_AFTER,
   CASE
    WHEN I.DEC_ID IS NULL THEN N'مبلغ واقعی سنوات و ریل منبع ثبت نشده؛ اعمال ممنوع'
    WHEN I.SOURCE_RAIL IS NULL OR I.SOURCE_RAIL NOT IN('NOMINAL','OFFICIAL','BOTH') THEN N'ریل منبع باید NOMINAL، OFFICIAL یا BOTH باشد'
    WHEN I.SOURCE_RAIL IN('NOMINAL','BOTH') AND (BN.AMOUNT IS NULL OR I.NOMINAL_SENIORITY_DAILY IS NULL) THEN N'پایه یا سنوات اسمی ناقص است'
    WHEN I.SOURCE_RAIL IN('OFFICIAL','BOTH') AND (BO.AMOUNT IS NULL OR I.OFFICIAL_SENIORITY_DAILY IS NULL) THEN N'پایه یا سنوات رسمی ناقص است'
    WHEN ISNULL(I.NOMINAL_SENIORITY_DAILY,0)<0 OR ISNULL(I.OFFICIAL_SENIORITY_DAILY,0)<0 THEN N'سنوات منفی مجاز نیست'
    WHEN ISNULL(I.NOMINAL_SENIORITY_DAILY,0)>ISNULL(BN.AMOUNT,0) OR ISNULL(I.OFFICIAL_SENIORITY_DAILY,0)>ISNULL(BO.AMOUNT,0) THEN N'سنوات از پایه ریل مربوط بیشتر است'
    WHEN I.IS_APPROVED=0 THEN N'در انتظار تأیید'
    WHEN L.DEC_ID IS NOT NULL THEN N'قبلاً اعمال شده'
    WHEN S.ITEM_ID IS NOT NULL THEN N'پایه سنوات از قبل در حکم وجود دارد'
    ELSE N'آماده اعمال' END MIGRATION_STATUS
 FROM dbo.PAY2_DECREE D
 JOIN dbo.PAY2_EMPLOYEE E ON E.EMP_ID=D.EMP_ID
 LEFT JOIN dbo.PAY2_SANOVAT_MIGRATION_INPUT I ON I.DEC_ID=D.DEC_ID
 LEFT JOIN dbo.PAY2_DECREE_LINE BN ON BN.DEC_ID=D.DEC_ID AND BN.ITEM_ID=(SELECT ITEM_ID FROM dbo.PAY2_ITEM_DEF WHERE ITEM_CODE='BASE_SAL')
 LEFT JOIN dbo.PAY2_DECREE_LINE BO ON BO.DEC_ID=D.DEC_ID AND BO.ITEM_ID=(SELECT ITEM_ID FROM dbo.PAY2_ITEM_DEF WHERE ITEM_CODE='BASE_SAL_B')
 LEFT JOIN dbo.PAY2_DECREE_LINE S ON S.DEC_ID=D.DEC_ID AND S.ITEM_ID=@ItemId
 LEFT JOIN dbo.PAY2_SANOVAT_MIGRATION_LOG L ON L.DEC_ID=D.DEC_ID
 WHERE D.IS_CONFIRMED=1 AND D.EFF_FROM<=@AsOf AND (D.EFF_TO IS NULL OR D.EFF_TO>=@AsOf) ORDER BY E.LAST_NAME,E.FIRST_NAME,D.EFF_FROM;
END;
GO

CREATE OR ALTER PROCEDURE dbo.SP_PAY2_APPLY_SANOVAT_MIGRATION @APPLIED_BY INT=NULL
AS
BEGIN
 SET NOCOUNT ON; SET XACT_ABORT ON;
 BEGIN TRY
  BEGIN TRANSACTION;
  DECLARE @ItemId INT=(SELECT ITEM_ID FROM dbo.PAY2_ITEM_DEF WITH(UPDLOCK,HOLDLOCK) WHERE ITEM_CODE='SANOVAT_PAYE');
  DECLARE @AsOf BIGINT=ISNULL((SELECT MAX(PERIOD_DATE)+31 FROM dbo.PAY2_PERIOD),99991231);
  IF @ItemId IS NULL THROW 51000,N'آیتم SANOVAT_PAYE نصب نشده است.',1;
  IF EXISTS(
    SELECT 1 FROM dbo.PAY2_SANOVAT_MIGRATION_INPUT I
    LEFT JOIN dbo.PAY2_DECREE_LINE BN ON BN.DEC_ID=I.DEC_ID AND BN.ITEM_ID=(SELECT ITEM_ID FROM dbo.PAY2_ITEM_DEF WHERE ITEM_CODE='BASE_SAL')
    LEFT JOIN dbo.PAY2_DECREE_LINE BO ON BO.DEC_ID=I.DEC_ID AND BO.ITEM_ID=(SELECT ITEM_ID FROM dbo.PAY2_ITEM_DEF WHERE ITEM_CODE='BASE_SAL_B')
    JOIN dbo.PAY2_DECREE D ON D.DEC_ID=I.DEC_ID AND D.IS_CONFIRMED=1 AND D.EFF_FROM<=@AsOf AND (D.EFF_TO IS NULL OR D.EFF_TO>=@AsOf)
    WHERE I.IS_APPROVED=1 AND (I.SOURCE_RAIL IS NULL OR I.SOURCE_RAIL NOT IN('NOMINAL','OFFICIAL','BOTH')
      OR (I.SOURCE_RAIL IN('NOMINAL','BOTH') AND (BN.AMOUNT IS NULL OR I.NOMINAL_SENIORITY_DAILY IS NULL OR I.NOMINAL_SENIORITY_DAILY<0 OR I.NOMINAL_SENIORITY_DAILY>BN.AMOUNT))
      OR (I.SOURCE_RAIL IN('OFFICIAL','BOTH') AND (BO.AMOUNT IS NULL OR I.OFFICIAL_SENIORITY_DAILY IS NULL OR I.OFFICIAL_SENIORITY_DAILY<0 OR I.OFFICIAL_SENIORITY_DAILY>BO.AMOUNT))))
   THROW 51001,N'ریل منبع یا مبلغ سنوات کامل/معتبر نیست؛ ابتدا Preview را بررسی کنید.',1;

  DECLARE @W TABLE(DEC_ID INT PRIMARY KEY,SOURCE_RAIL NVARCHAR(10),NB DECIMAL(18,2),NS DECIMAL(18,2),NA DECIMAL(18,2),OB DECIMAL(18,2),OS DECIMAL(18,2),OA DECIMAL(18,2));
  INSERT @W
  SELECT I.DEC_ID,I.SOURCE_RAIL,BN.AMOUNT,CASE WHEN I.SOURCE_RAIL IN('NOMINAL','BOTH') THEN I.NOMINAL_SENIORITY_DAILY ELSE 0 END,
    CASE WHEN I.SOURCE_RAIL IN('NOMINAL','BOTH') THEN BN.AMOUNT-I.NOMINAL_SENIORITY_DAILY ELSE BN.AMOUNT END,
    BO.AMOUNT,CASE WHEN I.SOURCE_RAIL IN('OFFICIAL','BOTH') THEN I.OFFICIAL_SENIORITY_DAILY ELSE 0 END,
    CASE WHEN I.SOURCE_RAIL IN('OFFICIAL','BOTH') THEN BO.AMOUNT-I.OFFICIAL_SENIORITY_DAILY ELSE BO.AMOUNT END
  FROM dbo.PAY2_SANOVAT_MIGRATION_INPUT I
  JOIN dbo.PAY2_DECREE D ON D.DEC_ID=I.DEC_ID AND D.IS_CONFIRMED=1 AND D.EFF_FROM<=@AsOf AND (D.EFF_TO IS NULL OR D.EFF_TO>=@AsOf)
  LEFT JOIN dbo.PAY2_DECREE_LINE BN ON BN.DEC_ID=I.DEC_ID AND BN.ITEM_ID=(SELECT ITEM_ID FROM dbo.PAY2_ITEM_DEF WHERE ITEM_CODE='BASE_SAL')
  LEFT JOIN dbo.PAY2_DECREE_LINE BO ON BO.DEC_ID=I.DEC_ID AND BO.ITEM_ID=(SELECT ITEM_ID FROM dbo.PAY2_ITEM_DEF WHERE ITEM_CODE='BASE_SAL_B')
  LEFT JOIN dbo.PAY2_DECREE_LINE S ON S.DEC_ID=I.DEC_ID AND S.ITEM_ID=@ItemId
  LEFT JOIN dbo.PAY2_SANOVAT_MIGRATION_LOG L ON L.DEC_ID=I.DEC_ID
  WHERE I.IS_APPROVED=1 AND S.ITEM_ID IS NULL AND L.DEC_ID IS NULL;

  UPDATE B SET AMOUNT=W.NA FROM dbo.PAY2_DECREE_LINE B JOIN @W W ON W.DEC_ID=B.DEC_ID JOIN dbo.PAY2_ITEM_DEF X ON X.ITEM_ID=B.ITEM_ID AND X.ITEM_CODE='BASE_SAL' WHERE W.SOURCE_RAIL IN('NOMINAL','BOTH');
  UPDATE B SET AMOUNT=W.OA FROM dbo.PAY2_DECREE_LINE B JOIN @W W ON W.DEC_ID=B.DEC_ID JOIN dbo.PAY2_ITEM_DEF X ON X.ITEM_ID=B.ITEM_ID AND X.ITEM_CODE='BASE_SAL_B' WHERE W.SOURCE_RAIL IN('OFFICIAL','BOTH');
  INSERT dbo.PAY2_DECREE_LINE(DEC_ID,ITEM_ID,AMOUNT,NOMINAL_AMOUNT_OV,OFFICIAL_AMOUNT_OV) SELECT DEC_ID,@ItemId,OS,NS,OS FROM @W;
  IF EXISTS(SELECT 1 FROM @W WHERE (NB IS NOT NULL AND NB<>NA+NS) OR (OB IS NOT NULL AND OB<>OA+OS)) THROW 51002,N'کنترل مستقل تساوی ریل اسمی/رسمی ناموفق بود.',1;
  INSERT dbo.PAY2_SANOVAT_MIGRATION_LOG(DEC_ID,SOURCE_RAIL,NOMINAL_BASE_BEFORE,NOMINAL_SENIORITY,NOMINAL_BASE_AFTER,OFFICIAL_BASE_BEFORE,OFFICIAL_SENIORITY,OFFICIAL_BASE_AFTER,APPLIED_BY)
   SELECT DEC_ID,SOURCE_RAIL,NB,NS,NA,OB,OS,OA,@APPLIED_BY FROM @W;
  COMMIT; SELECT COUNT(*) APPLIED_COUNT FROM @W;
 END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH
END;
GO
