/* Read-only release gate. Execute after ScriptSqly on the customer's database clone.
   Engine v3 runs are strict. Legacy runs are reported separately and are never required
   to contain columns that did not exist when they were finalized. */
SET NOCOUNT ON;

-- Preflight: Runهای v2 قدیمی فاقد Snapshotهای افزوده‌شده را فقط گزارش می‌کند؛ هیچ Backfill انجام نمی‌شود.
SELECT R.RUN_ID,R.PER_ID,R.STATUS,R.PAYROLL_ENGINE_VERSION,
       COUNT(RL.EMP_ID) RUN_LINE_COUNT,COUNT(ES.EMP_ID) EMP_SNAPSHOT_COUNT
FROM dbo.PAY2_RUN R
LEFT JOIN dbo.PAY2_RUN_LINE RL ON RL.RUN_ID=R.RUN_ID
LEFT JOIN dbo.PAY2_RUN_EMP_SNAPSHOT ES ON ES.RUN_ID=RL.RUN_ID AND ES.EMP_ID=RL.EMP_ID
WHERE R.PAYROLL_ENGINE_VERSION=2
GROUP BY R.RUN_ID,R.PER_ID,R.STATUS,R.PAYROLL_ENGINE_VERSION
HAVING COUNT(RL.EMP_ID)<>COUNT(ES.EMP_ID);


IF NOT EXISTS(SELECT 1 FROM dbo.PAY2_RUN WHERE PAYROLL_ENGINE_VERSION>=3)
 THROW 52000,N'هیچ Run آزمایشی با موتور Snapshot نسخه 3 در Clone وجود ندارد.',1;

;WITH V3Detail AS
(
 SELECT D.* FROM dbo.PAY2_RUN_DETAIL D JOIN dbo.PAY2_RUN R ON R.RUN_ID=D.RUN_ID WHERE R.PAYROLL_ENGINE_VERSION>=3
), V3Rail AS
(
 SELECT RUN_ID,EMP_ID,
  MAX(CASE WHEN ITEM_CODE_SNAP='BASE_SAL' AND NOMINAL_AMOUNT IS NOT NULL THEN 1 ELSE 0 END) HAS_N,
  MAX(CASE WHEN ITEM_CODE_SNAP='BASE_SAL_B' AND AMOUNT IS NOT NULL THEN 1 ELSE 0 END) HAS_O,
  MAX(CASE WHEN ITEM_CODE_SNAP='SANOVAT_PAYE' AND NOMINAL_AMOUNT<>AMOUNT THEN 1 ELSE 0 END) DUAL_SEN
 FROM V3Detail GROUP BY RUN_ID,EMP_ID
)
SELECT * INTO #V3Rail FROM V3Rail;

IF EXISTS(SELECT 1 FROM dbo.PAY2_RUN_DETAIL D JOIN dbo.PAY2_RUN R ON R.RUN_ID=D.RUN_ID WHERE R.PAYROLL_ENGINE_VERSION>=3 AND
 (D.NOMINAL_AMOUNT IS NULL OR D.ITEM_CODE_SNAP IS NULL OR D.ITEM_NAME_SNAP IS NULL OR D.ITEM_TYPE_SNAP IS NULL OR D.CALC_BASIS_SNAP IS NULL OR D.INS_SUBJECT_AMOUNT IS NULL OR D.TAX_SUBJECT_AMOUNT IS NULL))
 THROW 52001,N'Snapshot یک ردیف Engine v3 ناقص است.',1;
IF EXISTS(SELECT 1 FROM dbo.PAY2_RUN_LINE RL JOIN dbo.PAY2_RUN R ON R.RUN_ID=RL.RUN_ID LEFT JOIN dbo.PAY2_RUN_EMP_SNAPSHOT ES ON ES.RUN_ID=RL.RUN_ID AND ES.EMP_ID=RL.EMP_ID WHERE R.PAYROLL_ENGINE_VERSION>=3 AND ES.RUN_ID IS NULL)
 THROW 52017,N'Snapshot مشخصات پرسنل یک Run نسخه 3 ناقص است.',1;
IF EXISTS(SELECT 1 FROM #V3Rail WHERE HAS_N=0 OR HAS_O=0) THROW 52002,N'Run نسخه 3 فاقد یکی از دو ریل است.',1;
IF NOT EXISTS(SELECT 1 FROM dbo.PAY2_RUN_LINE RL JOIN dbo.PAY2_RUN R ON R.RUN_ID=RL.RUN_ID WHERE R.PAYROLL_ENGINE_VERSION>=3 AND RL.NOMINAL_DAYS<>RL.WORK_DAYS)
 THROW 52003,N'سناریوی Snapshot شده DAYS != DAYSB در Run نسخه 3 وجود ندارد.',1;
IF NOT EXISTS(SELECT 1 FROM #V3Rail WHERE DUAL_SEN=1) THROW 52004,N'سنوات متفاوت در دو ریل نسخه 3 وجود ندارد.',1;

-- Exact official/nominal gross and monetary subject reconciliation for v3 only.
IF EXISTS(SELECT 1 FROM dbo.PAY2_RUN_LINE RL JOIN dbo.PAY2_RUN R ON R.RUN_ID=RL.RUN_ID CROSS APPLY
 (SELECT SUM(CASE WHEN D.ITEM_TYPE_SNAP IN(1,2) AND D.ITEM_CODE_SNAP<>'BASE_SAL' THEN D.AMOUNT ELSE 0 END) V FROM dbo.PAY2_RUN_DETAIL D WHERE D.RUN_ID=RL.RUN_ID AND D.EMP_ID=RL.EMP_ID) X
 WHERE R.PAYROLL_ENGINE_VERSION>=3 AND ABS(ISNULL(X.V,0)+ISNULL(RL.ROUNDING_ADJ,0)-RL.GROSS_PAY)>1)
 THROW 52005,N'ناخالص رسمی Engine v3 با جزئیات رسمی تراز نیست.',1;
IF EXISTS(SELECT 1 FROM dbo.PAY2_RUN_LINE RL JOIN dbo.PAY2_RUN R ON R.RUN_ID=RL.RUN_ID CROSS APPLY
 (SELECT SUM(CASE WHEN D.ITEM_TYPE_SNAP IN(1,2) AND D.ITEM_CODE_SNAP<>'BASE_SAL_B' THEN D.NOMINAL_AMOUNT ELSE 0 END) V FROM dbo.PAY2_RUN_DETAIL D WHERE D.RUN_ID=RL.RUN_ID AND D.EMP_ID=RL.EMP_ID) X
 WHERE R.PAYROLL_ENGINE_VERSION>=3 AND ABS(ISNULL(X.V,0)-RL.NOMINAL_GROSS)>1)
 THROW 52006,N'ناخالص اسمی Engine v3 با جزئیات اسمی تراز نیست.',1;
IF EXISTS(SELECT 1 FROM dbo.PAY2_RUN_DETAIL D JOIN dbo.PAY2_RUN R ON R.RUN_ID=D.RUN_ID WHERE R.PAYROLL_ENGINE_VERSION>=3 AND (D.INS_SUBJECT_AMOUNT<0 OR D.TAX_SUBJECT_AMOUNT<0))
 THROW 52007,N'Snapshot مبلغ مشمول منفی است.',1;
IF EXISTS(SELECT 1 FROM dbo.PAY2_RUN_DETAIL D JOIN dbo.PAY2_RUN R ON R.RUN_ID=D.RUN_ID WHERE R.PAYROLL_ENGINE_VERSION>=3 AND D.ITEM_CODE_SNAP='BASE_SAL_B' AND (D.INS_SUBJECT_AMOUNT<>0 OR D.TAX_SUBJECT_AMOUNT<>0))
 THROW 52014,N'BASE_SAL_B رسمی وارد مبلغ مشمول بیمه یا مالیات شده است.',1;

DECLARE @Ceiling BIGINT=TRY_CAST((SELECT CFG_VALUE FROM dbo.PAY2_CONFIG WHERE CFG_KEY='INS_CEILING_MONTHLY') AS BIGINT);
IF @Ceiling IS NOT NULL AND EXISTS(SELECT 1 FROM dbo.PAY2_RUN_LINE RL JOIN dbo.PAY2_RUN R ON R.RUN_ID=RL.RUN_ID WHERE R.PAYROLL_ENGINE_VERSION>=3 AND INS_BASE>CAST(@Ceiling/30.0*NOMINAL_DAYS AS BIGINT)) THROW 52008,N'سقف بیمه بر DAYS اسمی نقض شده است.',1;
IF EXISTS(SELECT 1 FROM dbo.PAY2_RUN_LINE RL JOIN dbo.PAY2_RUN R ON R.RUN_ID=RL.RUN_ID WHERE R.PAYROLL_ENGINE_VERSION>=3 AND (INS_EMPLOYER_BASE IS NULL OR INS_UNEMPLOYMENT IS NULL OR INS_EMPLOYER<>INS_EMPLOYER_BASE+INS_UNEMPLOYMENT)) THROW 52009,N'Snapshot بیمه کارفرما نامعتبر است.',1;
IF NOT EXISTS(SELECT 1 FROM dbo.PAY2_RUN_DETAIL D JOIN dbo.PAY2_RUN R ON R.RUN_ID=D.RUN_ID WHERE R.PAYROLL_ENGINE_VERSION>=3 AND D.INS_SUBJECT<>D.TAX_SUBJECT) THROW 52010,N'سناریوی INS_SUBJECT != TAX_SUBJECT نسخه 3 وجود ندارد.',1;

-- Insurance components must reconcile to the final capped/exempt INS_BASE used as DSW_MASH.
DECLARE @CeilingApply BIT=TRY_CAST((SELECT CFG_VALUE FROM dbo.PAY2_CONFIG WHERE CFG_KEY='INS_CEILING_APPLY') AS BIT);
IF EXISTS
(
 SELECT 1 FROM dbo.PAY2_RUN_LINE RL
 JOIN dbo.PAY2_RUN R ON R.RUN_ID=RL.RUN_ID
 JOIN dbo.PAY2_RUN_EMP_SNAPSHOT ES ON ES.RUN_ID=RL.RUN_ID AND ES.EMP_ID=RL.EMP_ID
 CROSS APPLY(SELECT ISNULL(SUM(D.INS_SUBJECT_AMOUNT),0) RAW_INS_COMPONENTS FROM dbo.PAY2_RUN_DETAIL D WHERE D.RUN_ID=RL.RUN_ID AND D.EMP_ID=RL.EMP_ID) C
 WHERE R.PAYROLL_ENGINE_VERSION>=3 AND RL.INS_BASE<>
  CASE WHEN ES.INS_TYPE_SNAP=3 THEN 0
       WHEN ISNULL(@CeilingApply,0)=1 AND @Ceiling IS NOT NULL AND C.RAW_INS_COMPONENTS>CAST(@Ceiling/30.0*RL.NOMINAL_DAYS AS BIGINT)
        THEN CAST(@Ceiling/30.0*RL.NOMINAL_DAYS AS BIGINT)
       ELSE C.RAW_INS_COMPONENTS END
)
 THROW 52015,N'اجزای مبلغ مشمول بیمه با INS_BASE نهایی/سقف‌شده (DSW_MASH) تراز نیست.',1;

IF EXISTS(SELECT 1 FROM dbo.PAY2_SANOVAT_MIGRATION_LOG WHERE (NOMINAL_BASE_BEFORE IS NOT NULL AND NOMINAL_BASE_BEFORE<>NOMINAL_BASE_AFTER+NOMINAL_SENIORITY) OR (OFFICIAL_BASE_BEFORE IS NOT NULL AND OFFICIAL_BASE_BEFORE<>OFFICIAL_BASE_AFTER+OFFICIAL_SENIORITY)) THROW 52011,N'تساوی Migration سنوات نقض شده است.',1;
IF EXISTS(SELECT 1 FROM dbo.PAY2_DECREE WHERE EFF_TO IS NOT NULL AND EFF_TO<EFF_FROM) THROW 52012,N'حکم با بازه تاریخی نامعتبر وجود دارد.',1;
IF EXISTS(SELECT 1 FROM dbo.PAY2_DECREE A JOIN dbo.PAY2_DECREE B ON B.EMP_ID=A.EMP_ID AND B.DEC_ID>A.DEC_ID AND B.IS_CONFIRMED=1 AND A.IS_CONFIRMED=1 AND A.EFF_FROM<=ISNULL(B.EFF_TO,99991231) AND ISNULL(A.EFF_TO,99991231)>=B.EFF_FROM)
 THROW 52018,N'دو حکم تأییدشده متداخل برای یک پرسنل وجود دارد.',1;
IF EXISTS(SELECT 1 FROM dbo.PAY2_RUN R JOIN dbo.PAY2_PERIOD P ON P.PER_ID=R.PER_ID WHERE R.PAYROLL_ENGINE_VERSION>=3 AND (R.WS_ID_SNAP IS NULL OR R.WS_ID_SNAP<>P.WS_ID))
 THROW 52019,N'کارگاه Snapshot شده Run با کارگاه دوره منطبق نیست.',1;
IF EXISTS(SELECT 1 FROM dbo.PAY2_RUN_LINE RL JOIN dbo.PAY2_RUN R ON R.RUN_ID=RL.RUN_ID WHERE R.PAYROLL_ENGINE_VERSION>=3 AND (RL.GROSS_PAY-RL.TOTAL_DED<>RL.NET_PAY OR RL.ROUNDING_ADJ IS NULL))
 THROW 52020,N'ROUNDING_ADJ یا تراز GROSS_PAY/TOTAL_DED/NET_PAY نامعتبر است.',1;
IF EXISTS(SELECT 1 FROM dbo.PAY2_SANOVAT_MIGRATION_LOG L JOIN dbo.PAY2_DECREE D ON D.DEC_ID=L.NEW_DEC_ID WHERE D.IS_CONFIRMED=1 AND (D.CONFIRMED_BY IS NULL OR D.CONFIRMED_AT IS NULL)) THROW 52013,N'حکم Migration فاقد اطلاعات تأیید است.',1;

-- Mandatory real numerical Beyzaei gate: nominal and official bases differ, but legal totals use nominal only.
IF NOT EXISTS
(
 SELECT 1 FROM dbo.PAY2_RUN_LINE RL JOIN dbo.PAY2_RUN R ON R.RUN_ID=RL.RUN_ID JOIN dbo.PAY2_RUN_EMP_SNAPSHOT E ON E.RUN_ID=RL.RUN_ID AND E.EMP_ID=RL.EMP_ID
 CROSS APPLY(SELECT SUM(CASE WHEN D.ITEM_CODE_SNAP='BASE_SAL' THEN D.NOMINAL_AMOUNT ELSE 0 END) BASE_N,
                    SUM(CASE WHEN D.ITEM_CODE_SNAP='BASE_SAL_B' THEN D.AMOUNT ELSE 0 END) BASE_O,
                    SUM(CASE WHEN D.ITEM_CODE_SNAP='BASE_SAL_B' THEN D.INS_SUBJECT_AMOUNT ELSE 0 END) BASE_O_INS,
                    SUM(CASE WHEN D.ITEM_CODE_SNAP='BASE_SAL_B' THEN D.TAX_SUBJECT_AMOUNT ELSE 0 END) BASE_O_TAX
             FROM dbo.PAY2_RUN_DETAIL D WHERE D.RUN_ID=RL.RUN_ID AND D.EMP_ID=RL.EMP_ID) B
 WHERE R.PAYROLL_ENGINE_VERSION>=3 AND (E.LAST_NAME LIKE N'%بیضائی%' OR E.LAST_NAME LIKE N'%بيضائي%')
   AND B.BASE_N<>B.BASE_O AND B.BASE_O_INS=0 AND B.BASE_O_TAX=0
)
 THROW 52016,N'سناریوی عددی Engine v3 آقای بیضائی با BASE_SAL متفاوت از BASE_SAL_B و حذف رسمی از خروجی قانونی وجود ندارد.',1;

SELECT RL.RUN_ID,E.EMP_CODE,E.LAST_NAME+N' '+E.FIRST_NAME FULL_NAME,B.BASE_N NOMINAL_BASE_BEFORE_OUTPUT,
 B.BASE_O OFFICIAL_BASE_EXCLUDED,B.BASE_N+B.SEN_N NOMINAL_WAGE_AFTER_SPLIT,RL.INS_BASE DSW_MASH_EXPECTED,RL.TAX_BASE,RL.NOMINAL_GROSS
FROM dbo.PAY2_RUN_LINE RL JOIN dbo.PAY2_RUN R ON R.RUN_ID=RL.RUN_ID JOIN dbo.PAY2_RUN_EMP_SNAPSHOT E ON E.RUN_ID=RL.RUN_ID AND E.EMP_ID=RL.EMP_ID
CROSS APPLY(SELECT SUM(CASE WHEN D.ITEM_CODE_SNAP='BASE_SAL' THEN D.NOMINAL_AMOUNT ELSE 0 END) BASE_N,
                   SUM(CASE WHEN D.ITEM_CODE_SNAP='BASE_SAL_B' THEN D.AMOUNT ELSE 0 END) BASE_O,
                   SUM(CASE WHEN D.ITEM_CODE_SNAP='SANOVAT_PAYE' THEN D.NOMINAL_AMOUNT ELSE 0 END) SEN_N
            FROM dbo.PAY2_RUN_DETAIL D WHERE D.RUN_ID=RL.RUN_ID AND D.EMP_ID=RL.EMP_ID) B
WHERE R.PAYROLL_ENGINE_VERSION>=3 AND (E.LAST_NAME LIKE N'%بیضائی%' OR E.LAST_NAME LIKE N'%بيضائي%') ORDER BY RL.RUN_ID;


-- موتور v3 باید محاسبه و Snapshot را از Temp Sourceهای یکسان بسازد.
DECLARE @CalcDefinition NVARCHAR(MAX)=OBJECT_DEFINITION(OBJECT_ID(N'dbo.SP_PAY2_CALC_RUN'));
IF @CalcDefinition NOT LIKE '%INTO #EmployeeSource%' OR @CalcDefinition NOT LIKE '%INTO #ItemDefSource%'
 THROW 52021,N'موتور v3 منابع پرسنل/اقلام را پیش از محاسبه Materialize نمی‌کند.',1;

-- شمارش‌های مورد انتظار WP/WH و DSKWOR؛ خروجی‌ساز باید دقیقاً همین تعداد رکورد بسازد.
IF EXISTS
(
 SELECT 1 FROM dbo.PAY2_RUN_LINE RL JOIN dbo.PAY2_RUN R ON R.RUN_ID=RL.RUN_ID
 JOIN dbo.PAY2_RUN_EMP_SNAPSHOT ES ON ES.RUN_ID=RL.RUN_ID AND ES.EMP_ID=RL.EMP_ID
 WHERE R.PAYROLL_ENGINE_VERSION>=3 AND
 ((ISNULL(ES.TAX_EXEMPT_SNAP,0)=0 AND (NULLIF(LTRIM(RTRIM(ES.NATIONAL_CODE)),N'') IS NULL OR NULLIF(LTRIM(RTRIM(ES.FIRST_NAME)),N'') IS NULL OR NULLIF(LTRIM(RTRIM(ES.LAST_NAME)),N'') IS NULL))
 OR (ISNULL(ES.INS_TYPE_SNAP,1)<>3 AND (NULLIF(LTRIM(RTRIM(ES.INS_CODE)),N'') IS NULL OR NULLIF(LTRIM(RTRIM(ES.FIRST_NAME)),N'') IS NULL OR NULLIF(LTRIM(RTRIM(ES.LAST_NAME)),N'') IS NULL OR NULLIF(LTRIM(RTRIM(ES.JOB_CODE_SNAP)),N'') IS NULL)))
)
 THROW 52022,N'Snapshot هویتی v3 برای WP/WH یا DSKWOR ناقص است.',1;

SELECT R.RUN_ID,
 SUM(CASE WHEN ES.TAX_EXEMPT_SNAP=0 THEN 1 ELSE 0 END) EXPECTED_WP_COUNT,
 SUM(CASE WHEN ES.TAX_EXEMPT_SNAP=0 THEN 1 ELSE 0 END) EXPECTED_WH_COUNT,
 SUM(CASE WHEN ES.INS_TYPE_SNAP<>3 THEN 1 ELSE 0 END) EXPECTED_DSKWOR_COUNT
FROM dbo.PAY2_RUN R JOIN dbo.PAY2_RUN_EMP_SNAPSHOT ES ON ES.RUN_ID=R.RUN_ID
WHERE R.PAYROLL_ENGINE_VERSION>=3 GROUP BY R.RUN_ID;

-- Engine v2 و Legacy فقط گزارش می‌شوند و مشمول الزامات Snapshot افزوده‌شده در v3 نیستند.
SELECT R.RUN_ID,R.STATUS,COUNT(*) DETAIL_COUNT,
 SUM(CASE WHEN D.NOMINAL_AMOUNT IS NULL OR D.ITEM_CODE_SNAP IS NULL THEN 1 ELSE 0 END) LEGACY_INCOMPLETE_ROWS
FROM dbo.PAY2_RUN R LEFT JOIN dbo.PAY2_RUN_DETAIL D ON D.RUN_ID=R.RUN_ID
WHERE R.PAYROLL_ENGINE_VERSION IS NULL OR R.PAYROLL_ENGINE_VERSION<3
GROUP BY R.RUN_ID,R.STATUS ORDER BY R.RUN_ID;

SELECT N'PAY2 Engine v3 blocker release audit passed' RESULT;
DROP TABLE #V3Rail;
