/* Read-only release gate. Execute after ScriptSqly on the customer's database clone. */
SET NOCOUNT ON;

;WITH RailState AS(
 SELECT RL.RUN_ID,RL.EMP_ID,MAX(CASE WHEN D.ITEM_CODE_SNAP='BASE_SAL' AND D.NOMINAL_AMOUNT<>0 THEN 1 ELSE 0 END) HAS_N,
 MAX(CASE WHEN D.ITEM_CODE_SNAP='BASE_SAL_B' AND D.AMOUNT<>0 THEN 1 ELSE 0 END) HAS_O,
 MAX(CASE WHEN D.ITEM_CODE_SNAP='SANOVAT_PAYE' AND D.NOMINAL_AMOUNT<>D.AMOUNT THEN 1 ELSE 0 END) DUAL_SEN
 FROM dbo.PAY2_RUN_LINE RL LEFT JOIN dbo.PAY2_RUN_DETAIL D ON D.RUN_ID=RL.RUN_ID AND D.EMP_ID=RL.EMP_ID GROUP BY RL.RUN_ID,RL.EMP_ID
)
SELECT * INTO #RailState FROM RailState;
IF EXISTS(SELECT 1 FROM dbo.PAY2_RUN_DETAIL WHERE NOMINAL_AMOUNT IS NULL OR ITEM_CODE_SNAP IS NULL OR ITEM_TYPE_SNAP IS NULL OR CALC_BASIS_SNAP IS NULL) THROW 51999,N'Snapshot قانونی جزئیات ناقص است.',1;
IF NOT EXISTS(SELECT 1 FROM dbo.PAY2_RUN_LINE RL JOIN dbo.PAY2_RUN R ON R.RUN_ID=RL.RUN_ID JOIN dbo.PAY2_PERIOD P ON P.PER_ID=R.PER_ID JOIN dbo.PAY2_ATTENDANCE A ON A.PER_ID=P.PER_ID AND A.EMP_ID=RL.EMP_ID WHERE RL.NOMINAL_DAYS<>A.DAYSB) THROW 52000,N'سناریوی DAYS != DAYSB در Clone وجود ندارد.',1;
IF NOT EXISTS(SELECT 1 FROM #RailState WHERE HAS_N=1 AND HAS_O=1) THROW 52001,N'سناریوی هر دو ریل وجود ندارد.',1;
IF NOT EXISTS(SELECT 1 FROM #RailState WHERE HAS_N=1 AND HAS_O=0) THROW 52002,N'سناریوی تاریخی فقط BASE_SAL وجود ندارد.',1;
IF NOT EXISTS(SELECT 1 FROM #RailState WHERE HAS_N=0 AND HAS_O=1) THROW 52003,N'سناریوی تاریخی فقط BASE_SAL_B وجود ندارد.',1;
IF NOT EXISTS(SELECT 1 FROM #RailState WHERE DUAL_SEN=1) THROW 52004,N'سنوات متفاوت در دو ریل وجود ندارد.',1;

-- Exact official and nominal gross reconciliation.
IF EXISTS(SELECT 1 FROM dbo.PAY2_RUN_LINE RL CROSS APPLY(SELECT SUM(CASE WHEN D.ITEM_TYPE_SNAP IN(1,2) AND D.ITEM_CODE_SNAP<>'BASE_SAL' THEN D.AMOUNT ELSE 0 END) V,MAX(CASE WHEN D.ITEM_CODE_SNAP='BASE_SAL_B' AND D.AMOUNT<>0 THEN 1 ELSE 0 END) HB FROM dbo.PAY2_RUN_DETAIL D WHERE D.RUN_ID=RL.RUN_ID AND D.EMP_ID=RL.EMP_ID) X WHERE X.HB=1 AND ABS(X.V+ISNULL(RL.ROUNDING_ADJ,0)-RL.GROSS_PAY)>1) THROW 52005,N'ناخالص رسمی با جزئیات رسمی تراز نیست.',1;
IF EXISTS(SELECT 1 FROM dbo.PAY2_RUN_LINE RL CROSS APPLY(SELECT SUM(CASE WHEN D.ITEM_TYPE_SNAP IN(1,2) AND D.ITEM_CODE_SNAP<>'BASE_SAL_B' THEN D.NOMINAL_AMOUNT ELSE 0 END) V FROM dbo.PAY2_RUN_DETAIL D WHERE D.RUN_ID=RL.RUN_ID AND D.EMP_ID=RL.EMP_ID) X WHERE RL.NOMINAL_GROSS IS NOT NULL AND (X.V IS NULL OR ABS(X.V-RL.NOMINAL_GROSS)>1)) THROW 52006,N'ناخالص اسمی با NOMINAL_AMOUNT تراز نیست.',1;

-- Insurance ceiling and exact premium snapshots.
DECLARE @Ceiling BIGINT=TRY_CAST((SELECT CFG_VALUE FROM dbo.PAY2_CONFIG WHERE CFG_KEY='INS_CEILING_MONTHLY') AS BIGINT);
IF @Ceiling IS NOT NULL AND EXISTS(SELECT 1 FROM dbo.PAY2_RUN_LINE WHERE NOMINAL_DAYS IS NOT NULL AND INS_BASE>CAST(@Ceiling/30.0*NOMINAL_DAYS AS BIGINT)) THROW 52007,N'سقف بیمه بر DAYS نقض شده است.',1;
IF EXISTS(SELECT 1 FROM dbo.PAY2_RUN_LINE WHERE NOMINAL_GROSS IS NOT NULL AND (INS_EMPLOYER_BASE IS NULL OR INS_UNEMPLOYMENT IS NULL OR INS_EMPLOYER<>INS_EMPLOYER_BASE+INS_UNEMPLOYMENT)) THROW 52008,N'Snapshot تفکیک بیمه کارفرما نامعتبر است.',1;
IF EXISTS(SELECT 1 FROM dbo.PAY2_RUN_LINE RL JOIN dbo.PAY2_EMPLOYEE E ON E.EMP_ID=RL.EMP_ID WHERE E.IS_MANAGER=1 AND ISNULL(RL.INS_UNEMPLOYMENT,0)<>0) THROW 52009,N'برای مدیر بیمه بیکاری ثبت شده است.',1;

-- A differing insurance/tax classification must exist, and snapshots must remain independent of current ITEM_DEF.
IF NOT EXISTS(SELECT 1 FROM dbo.PAY2_RUN_DETAIL WHERE INS_SUBJECT<>TAX_SUBJECT) THROW 52010,N'سناریوی INS_SUBJECT != TAX_SUBJECT وجود ندارد.',1;
IF NOT EXISTS(SELECT 1 FROM dbo.PAY2_RUN_DETAIL D JOIN dbo.PAY2_ITEM_DEF I ON I.ITEM_ID=D.ITEM_ID WHERE D.INS_SUBJECT<>I.INS_SUBJECT OR D.TAX_SUBJECT<>I.TAX_SUBJECT) THROW 52011,N'سناریوی تاریخی پس از تغییر ITEM_DEF وجود ندارد.',1;

-- Real Beyzaei numerical evidence, not merely name existence.
IF NOT EXISTS(SELECT 1 FROM dbo.PAY2_EMPLOYEE WHERE LAST_NAME LIKE N'%بیضائی%' OR LAST_NAME LIKE N'%بيضائي%') THROW 52012,N'رکورد آقای بیضائی در Clone یافت نشد.',1;
IF NOT EXISTS(SELECT 1 FROM dbo.PAY2_RUN_LINE RL JOIN dbo.PAY2_EMPLOYEE E ON E.EMP_ID=RL.EMP_ID CROSS APPLY(SELECT SUM(CASE WHEN D.ITEM_CODE_SNAP='BASE_SAL' THEN D.NOMINAL_AMOUNT ELSE 0 END) N,SUM(CASE WHEN D.ITEM_CODE_SNAP='BASE_SAL_B' THEN D.AMOUNT ELSE 0 END) O FROM dbo.PAY2_RUN_DETAIL D WHERE D.RUN_ID=RL.RUN_ID AND D.EMP_ID=RL.EMP_ID) B WHERE (E.LAST_NAME LIKE N'%بیضائی%' OR E.LAST_NAME LIKE N'%بيضائي%') AND B.N<>B.O) THROW 52013,N'سناریوی عددی BASE_SAL != BASE_SAL_B برای آقای بیضائی وجود ندارد.',1;
IF EXISTS(SELECT 1 FROM dbo.PAY2_SANOVAT_MIGRATION_LOG WHERE (NOMINAL_BASE_BEFORE IS NOT NULL AND NOMINAL_BASE_BEFORE<>NOMINAL_BASE_AFTER+NOMINAL_SENIORITY) OR (OFFICIAL_BASE_BEFORE IS NOT NULL AND OFFICIAL_BASE_BEFORE<>OFFICIAL_BASE_AFTER+OFFICIAL_SENIORITY)) THROW 52014,N'تساوی قبل/بعد Migration سنوات در یکی از ریل‌ها نقض شده است.',1;
SELECT RL.RUN_ID,E.EMP_CODE,E.LAST_NAME+N' '+E.FIRST_NAME FULL_NAME,RL.NOMINAL_DAYS,RL.WORK_DAYS,RL.NOMINAL_GROSS,RL.GROSS_PAY,RL.INS_BASE,RL.INS_WORKER,RL.TAX_AMOUNT,RL.TOTAL_DED,RL.NET_PAY
FROM dbo.PAY2_RUN_LINE RL JOIN dbo.PAY2_EMPLOYEE E ON E.EMP_ID=RL.EMP_ID WHERE E.LAST_NAME LIKE N'%بیضائی%' OR E.LAST_NAME LIKE N'%بيضائي%' ORDER BY RL.RUN_ID;

-- Preview must be invoked separately with the approved explicit effective date:
-- EXEC dbo.SP_PAY2_PREVIEW_SANOVAT_MIGRATION @EFFECTIVE_FROM=1405MM01;
SELECT N'PAY2 blocker release audit passed' RESULT;
DROP TABLE #RailState;
